<!DOCTYPE html>
<html xmlns="http://www.w3.org/1999/xhtml" lang="en" xml:lang="en"><head>

<meta charset="utf-8">
<meta name="generator" content="quarto-1.6.42">

<meta name="viewport" content="width=device-width, initial-scale=1.0, user-scalable=yes">

<meta name="dcterms.date" content="2025-10-20">
<meta name="description" content="Student dropout prediction using progressively enriched multi-stage data as an example of neural network performance evaluation.">

<title>Predicting Student Dropout Risk with Neural Networks</title>
<style>
code{white-space: pre-wrap;}
span.smallcaps{font-variant: small-caps;}
div.columns{display: flex; gap: min(4vw, 1.5em);}
div.column{flex: auto; overflow-x: auto;}
div.hanging-indent{margin-left: 1.5em; text-indent: -1.5em;}
ul.task-list{list-style: none;}
ul.task-list li input[type="checkbox"] {
  width: 0.8em;
  margin: 0 0.8em 0.2em -1em; /* quarto-specific, see https://github.com/quarto-dev/quarto-cli/issues/4556 */ 
  vertical-align: middle;
}
/* CSS for syntax highlighting */
pre > code.sourceCode { white-space: pre; position: relative; }
pre > code.sourceCode > span { line-height: 1.25; }
pre > code.sourceCode > span:empty { height: 1.2em; }
.sourceCode { overflow: visible; }
code.sourceCode > span { color: inherit; text-decoration: inherit; }
div.sourceCode { margin: 1em 0; }
pre.sourceCode { margin: 0; }
@media screen {
div.sourceCode { overflow: auto; }
}
@media print {
pre > code.sourceCode { white-space: pre-wrap; }
pre > code.sourceCode > span { display: inline-block; text-indent: -5em; padding-left: 5em; }
}
pre.numberSource code
  { counter-reset: source-line 0; }
pre.numberSource code > span
  { position: relative; left: -4em; counter-increment: source-line; }
pre.numberSource code > span > a:first-child::before
  { content: counter(source-line);
    position: relative; left: -1em; text-align: right; vertical-align: baseline;
    border: none; display: inline-block;
    -webkit-touch-callout: none; -webkit-user-select: none;
    -khtml-user-select: none; -moz-user-select: none;
    -ms-user-select: none; user-select: none;
    padding: 0 4px; width: 4em;
  }
pre.numberSource { margin-left: 3em;  padding-left: 4px; }
div.sourceCode
  {   }
@media screen {
pre > code.sourceCode > span > a:first-child::before { text-decoration: underline; }
}
/* CSS for citations */
div.csl-bib-body { }
div.csl-entry {
  clear: both;
  margin-bottom: 0em;
}
.hanging-indent div.csl-entry {
  margin-left:2em;
  text-indent:-2em;
}
div.csl-left-margin {
  min-width:2em;
  float:left;
}
div.csl-right-inline {
  margin-left:2em;
  padding-left:1em;
}
div.csl-indent {
  margin-left: 2em;
}</style>


<script src="https://cdnjs.cloudflare.com/ajax/libs/jquery/3.5.1/jquery.min.js" integrity="sha512-bLT0Qm9VnAYZDflyKcBaQ2gg0hSYNQrJ8RilYldYQ1FxQYoCLtUjuuRuZo+fjqhx/qtq/1itJ0C2ejDxltZVFg==" crossorigin="anonymous"></script><script src="../site_libs/quarto-nav/quarto-nav.js"></script>
<script src="../site_libs/quarto-nav/headroom.min.js"></script>
<script src="../site_libs/clipboard/clipboard.min.js"></script>
<script src="../site_libs/quarto-search/autocomplete.umd.js"></script>
<script src="../site_libs/quarto-search/fuse.min.js"></script>
<script src="../site_libs/quarto-search/quarto-search.js"></script>
<meta name="quarto:offset" content="../">
<script src="../site_libs/quarto-html/quarto.js"></script>
<script src="../site_libs/quarto-html/popper.min.js"></script>
<script src="../site_libs/quarto-html/tippy.umd.min.js"></script>
<script src="../site_libs/quarto-html/anchor.min.js"></script>
<link href="../site_libs/quarto-html/tippy.css" rel="stylesheet">
<link href="../site_libs/quarto-html/quarto-syntax-highlighting-2f5df379a58b258e96c21c0638c20c03.css" rel="stylesheet" id="quarto-text-highlighting-styles">
<script src="../site_libs/bootstrap/bootstrap.min.js"></script>
<link href="../site_libs/bootstrap/bootstrap-icons.css" rel="stylesheet">
<link href="../site_libs/bootstrap/bootstrap-c7f4df60c4f27e6d4d5319664186fcad.min.css" rel="stylesheet" append-hash="true" id="quarto-bootstrap" data-mode="light">
<script id="quarto-search-options" type="application/json">{
  "location": "navbar",
  "copy-button": false,
  "collapse-after": 3,
  "panel-placement": "end",
  "type": "overlay",
  "limit": 50,
  "keyboard-shortcut": [
    "f",
    "/",
    "s"
  ],
  "show-item-context": false,
  "language": {
    "search-no-results-text": "No results",
    "search-matching-documents-text": "matching documents",
    "search-copy-link-title": "Copy link to search",
    "search-hide-matches-text": "Hide additional matches",
    "search-more-match-text": "more match in this document",
    "search-more-matches-text": "more matches in this document",
    "search-clear-button-title": "Clear",
    "search-text-placeholder": "",
    "search-detached-cancel-button-title": "Cancel",
    "search-submit-button-title": "Submit",
    "search-label": "Search"
  }
}</script>
<script src="https://cdnjs.cloudflare.com/ajax/libs/require.js/2.3.6/require.min.js" integrity="sha512-c3Nl8+7g4LMSTdrm621y7kf9v3SDPnhxLNhcjFJbKECVnmZHTdo+IRO05sNLTH/D3vA6u1X32ehoLC7WFVdheg==" crossorigin="anonymous"></script>

<script type="application/javascript">define('jquery', [],function() {return window.jQuery;})</script>
<style>
figcaption.quarto-float-caption {
  text-align: left !important;
}
.quarto-figure-center {
  text-align: left !important;
}
.fig-label-left-edge {
  text-align: left !important;
  margin-left: calc(-46vw + 50%);
  width: 100vw;
  position: relative;
  left: 0;
}
/* Numbered references */
#refs .csl-entry {
  padding-left: 2em;
  text-indent: -2em;
  margin-bottom: 1em;
}
#refs {
  counter-reset: ref-counter;
}
#refs .csl-entry::before {
  counter-increment: ref-counter;
  content: counter(ref-counter) ". ";
  margin-right: 0.5em;
}
</style>


<link rel="stylesheet" href="../styles/styles.css">
</head>

<body class="nav-fixed">

<div id="quarto-search-results"></div>
  <header id="quarto-header" class="headroom fixed-top">
    <nav class="navbar navbar-expand-lg " data-bs-theme="dark">
      <div class="navbar-container container-fluid">
            <div id="quarto-search" class="" title="Search"></div>
          <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarCollapse" aria-controls="navbarCollapse" role="menu" aria-expanded="false" aria-label="Toggle navigation" onclick="if (window.quartoToggleHeadroom) { window.quartoToggleHeadroom(); }">
  <span class="navbar-toggler-icon"></span>
</button>
          <div class="collapse navbar-collapse" id="navbarCollapse">
            <ul class="navbar-nav navbar-nav-scroll me-auto">
  <li class="nav-item">
    <a class="nav-link" href="../index.html"> 
<span class="menu-text">Home</span></a>
  </li>  
  <li class="nav-item">
    <a class="nav-link" href="../projects.html"> 
<span class="menu-text">Projects</span></a>
  </li>  
  <li class="nav-item">
    <a class="nav-link" href="../blog.html"> 
<span class="menu-text">Blog</span></a>
  </li>  
  <li class="nav-item">
    <a class="nav-link" href="../cv.html"> 
<span class="menu-text">CV</span></a>
  </li>  
</ul>
          </div> <!-- /navcollapse -->
            <div class="quarto-navbar-tools">
</div>
      </div> <!-- /container-fluid -->
    </nav>
</header>
<!-- content -->
<div id="quarto-content" class="quarto-container page-columns page-rows-contents page-layout-full page-navbar">
<!-- sidebar -->
<!-- margin-sidebar -->
    
<!-- main -->
<main class="content column-page" id="quarto-document-content">

<header id="title-block-header" class="quarto-title-block default">
<div class="quarto-title">
<h1 class="title">Predicting Student Dropout Risk with Neural Networks</h1>
  <div class="quarto-categories">
    <div class="quarto-category">Machine Learning</div>
    <div class="quarto-category">Neural Networks</div>
    <div class="quarto-category">Predictive Analytics</div>
    <div class="quarto-category">Python</div>
  </div>
  </div>

<div>
  <div class="description">
    Student dropout prediction using progressively enriched multi-stage data as an example of neural network performance evaluation.
  </div>
</div>


<div class="quarto-title-meta column-page">

    
    <div>
    <div class="quarto-title-meta-heading">Published</div>
    <div class="quarto-title-meta-contents">
      <p class="date">October 20, 2025</p>
    </div>
  </div>
  
    
  </div>
  


</header>


<p><a href="../projects/categories/machine-learning-ai.html" class="back-link">← Back to Machine Learning Projects</a></p>
<section id="introduction" class="level2">
<h2 class="anchored" data-anchor-id="introduction">Introduction</h2>
<p>Student dropout in higher education represents a critical challenge affecting individuals, institutions, and society. Understanding factors that contribute to dropout risk and developing accurate predictive models enables timely interventions that can improve student outcomes and institutional retention rates <span class="citation" data-cites="goren2024early">(<a href="#ref-goren2024early" role="doc-biblioref">Goren, Cohen, and Rubinstein 2024</a>)</span>. Early identification of at-risk students allows institutions to deploy targeted support services, academic advising, tutoring, financial aid, mental health resources, when they can have maximum impact.</p>
<p>Traditional dropout prediction approaches rely on demographic features and early engagement metrics available at enrollment. However, these features provide limited predictive signal, as dropout decisions often crystallize after academic performance patterns emerge mid-semester. This creates a tension between early intervention (when support can help most) and prediction accuracy (which improves with more data). Progressive data enrichment, incorporating features as they become available throughout the term, offers a potential resolution, enabling institutions to update risk assessments as academic performance unfolds.</p>
<p>This analysis evaluates neural networks for student dropout prediction using three progressive data stages: Stage 1 (enrollment features), Stage 2 (mid-semester engagement), and Stage 3 (end-of-semester academic performance). We systematically compare base and hyperparameter-tuned models across all stages, quantifying how prediction accuracy evolves with data enrichment. Results demonstrate that comprehensive end-of-semester data enables exceptional performance (ROC-AUC &gt;0.98, F1 &gt;0.97), substantially outperforming early-stage predictions (ROC-AUC ~0.85). Surprisingly, hyperparameter optimization yields minimal gains across all stages (&lt;1% improvement), suggesting data quality matters more than architectural fine-tuning for this prediction task.</p>
<p>This work was completed as part of a Professional Certificate in Data Science with Machine Learning and AI from the University of Cambridge. Due to confidentiality requirements, I cannot share the dataset or complete project details, but I present the methodology and selected results that showcase the techniques learned during the course.</p>
</section>
<section id="goals-and-objectives" class="level2">
<h2 class="anchored" data-anchor-id="goals-and-objectives">Goals and Objectives</h2>
<p>Here are the primary objectives for the entire project, however I will discuss on selected aspects of stage 3 data:</p>
<ol type="1">
<li><p><strong>Evaluate Neural Network Performance Across Progressive Data Stages</strong>: Assess how neural network models perform when trained on three distinct data stages representing different temporal points in the academic term (enrollment, mid-semester, end-of-semester), quantifying the trade-off between early prediction capability and model accuracy.</p></li>
<li><p><strong>Compare Base versus Hyperparameter-Tuned Models</strong>: Systematically evaluate whether hyperparameter optimization (learning rate, batch size, dropout rate, L1/L2 regularization) yields meaningful performance improvements over baseline neural network configurations for student dropout prediction.</p></li>
<li><p><strong>Analyze Model Performance on Imbalanced Educational Data</strong>: Evaluate neural network behavior when trained on imbalanced datasets typical of educational settings, assessing the models’ ability to learn effective decision boundaries for minority class (dropout) prediction.</p></li>
<li><p><strong>Provide Evidence-Based Model Selection Guidance</strong>: Deliver actionable recommendations for practitioners implementing dropout prediction systems, including optimal model configurations and data stage considerations for institutional deployment.</p></li>
</ol>
</section>
<section id="methods" class="level2">
<h2 class="anchored" data-anchor-id="methods">Methods</h2>
<section id="data-description-and-preprocessing" class="level3">
<h3 class="anchored" data-anchor-id="data-description-and-preprocessing">Data Description and Preprocessing</h3>
<p>The analysis utilized a longitudinal student dataset containing demographic, behavioral, and academic performance information. The dataset exhibited substantial class imbalance typical of institutional retention rates. Three progressive data stages simulated real-world temporal information availability: Stage 1 included demographic and early enrollment features; Stage 2 incorporated mid-semester engagement metrics including absence counts; Stage 3 added comprehensive end-of-semester academic performance indicators.</p>
<p>Preprocessing involved feature engineering transformations specific to each stage. For all stages high-cardinality features (&gt;200 unique values) including HomeState, HomeCity, and ProgressionDegree were removed to prevent overfitting and reduce dimensionality; DateOfBirth was converted to Age for improved feature interpretability. Critically, Stage 3 introduced academic performance metrics (AssessedModules, PassedModules, FailedModules) which were engineered into a composite feature RateModuleSuccess calculated as (PassedModules - FailedModules) / AssessedModules, capturing student success trajectory more parsimoniously than individual module counts. The Nationality feature was dropped from Stage 3 analysis due to extreme class imbalance. Features with &gt;50% missing values were removed, and rows with missing absence category values were excluded given their small proportion. Categorical features underwent one-hot encoding, while ordinal features (CourseLevel, absence categories) received ordinal encoding. All features underwent standardization using scikit-learn <span class="citation" data-cites="pedregosa2011scikitlearn">(<a href="#ref-pedregosa2011scikitlearn" role="doc-biblioref">Pedregosa et al. 2011</a>)</span> to ensure consistent neural network training.</p>
</section>
<section id="neural-network-architecture-and-training" class="level3">
<h3 class="anchored" data-anchor-id="neural-network-architecture-and-training">Neural Network Architecture and Training</h3>
<p>Multiple feedforward neural network architectures were systematically evaluated using TensorFlow/Keras <span class="citation" data-cites="abadi2016tensorflow">(<a href="#ref-abadi2016tensorflow" role="doc-biblioref">Abadi et al. 2016</a>)</span>. The implementation prioritized reproducibility through deterministic operations, with fixed random seeds across all randomness sources (Python, NumPy, TensorFlow) and enabled TensorFlow’s experimental deterministic operations mode. This ensures identical results across repeated runs, critical for fair model comparisons.</p>
<p>The dataset underwent hierarchical splitting into training (64%), validation (20%), and test (16%) sets using stratified random sampling to preserve class proportions across splits. Features were standardized using scikit-learn’s StandardScaler fitted exclusively on training data, with the same transformation applied to validation and test sets to prevent data leakage. This preprocessing pipeline ensures models encounter data distributions representative of real-world deployment scenarios.</p>
<div id="3f681ac8" class="cell" data-execution_count="1">
<div class="sourceCode cell-code" id="cb1"><pre class="sourceCode python code-overflow-wrap code-with-copy"><code class="sourceCode python"><span id="cb1-1"><a href="#cb1-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Split the data into features and target variable</span></span>
<span id="cb1-2"><a href="#cb1-2" aria-hidden="true" tabindex="-1"></a>X_s3 <span class="op">=</span> df3_filled.drop(columns<span class="op">=</span>[<span class="st">'CompletedCourse_Yes'</span>], axis<span class="op">=</span><span class="dv">1</span>, inplace<span class="op">=</span><span class="va">False</span>)</span>
<span id="cb1-3"><a href="#cb1-3" aria-hidden="true" tabindex="-1"></a>y_s3 <span class="op">=</span> df3_filled[<span class="st">'CompletedCourse_Yes'</span>]</span>
<span id="cb1-4"><a href="#cb1-4" aria-hidden="true" tabindex="-1"></a><span class="co"># Display the first few rows of the features and target variable</span></span>
<span id="cb1-5"><a href="#cb1-5" aria-hidden="true" tabindex="-1"></a>display(X_s3.head())  </span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
<div id="41363c35" class="cell" data-execution_count="2">
<div class="sourceCode cell-code" id="cb2"><pre class="sourceCode python code-overflow-wrap code-with-copy"><code class="sourceCode python"><span id="cb2-1"><a href="#cb2-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Split the data into training and validation sets</span></span>
<span id="cb2-2"><a href="#cb2-2" aria-hidden="true" tabindex="-1"></a>X_train_s3, X_val_s3, y_train_s3, y_val_s3 <span class="op">=</span> train_test_split(X_s3, y_s3, test_size<span class="op">=</span><span class="fl">0.2</span>, random_state<span class="op">=</span><span class="dv">42</span>)</span>
<span id="cb2-3"><a href="#cb2-3" aria-hidden="true" tabindex="-1"></a><span class="co"># Split the training data into training and test sets</span></span>
<span id="cb2-4"><a href="#cb2-4" aria-hidden="true" tabindex="-1"></a>X_train_s3, X_test_s3, y_train_s3, y_test_s3 <span class="op">=</span> train_test_split(X_train_s3, y_train_s3, test_size<span class="op">=</span><span class="fl">0.2</span>, random_state<span class="op">=</span><span class="dv">42</span>)</span>
<span id="cb2-5"><a href="#cb2-5" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb2-6"><a href="#cb2-6" aria-hidden="true" tabindex="-1"></a><span class="co"># Display the shapes of the training, validation, and test sets</span></span>
<span id="cb2-7"><a href="#cb2-7" aria-hidden="true" tabindex="-1"></a><span class="bu">print</span>(<span class="st">"Training set shape:"</span>, X_train_s3.shape, y_train_s3.shape)</span>
<span id="cb2-8"><a href="#cb2-8" aria-hidden="true" tabindex="-1"></a><span class="bu">print</span>(<span class="st">"Validation set shape:"</span>, X_val_s3.shape, y_val_s3.shape)</span>
<span id="cb2-9"><a href="#cb2-9" aria-hidden="true" tabindex="-1"></a><span class="bu">print</span>(<span class="st">"Test set shape:"</span>, X_test_s3.shape, y_test_s3.shape)</span>
<span id="cb2-10"><a href="#cb2-10" aria-hidden="true" tabindex="-1"></a><span class="co"># Check the distribution of the target variable in the training set</span></span>
<span id="cb2-11"><a href="#cb2-11" aria-hidden="true" tabindex="-1"></a><span class="bu">print</span>(<span class="st">"Training set target variable distribution:"</span>)</span>
<span id="cb2-12"><a href="#cb2-12" aria-hidden="true" tabindex="-1"></a><span class="bu">print</span>(y_train_s3.value_counts(normalize<span class="op">=</span><span class="va">True</span>))</span>
<span id="cb2-13"><a href="#cb2-13" aria-hidden="true" tabindex="-1"></a><span class="co"># Check the distribution of the target variable in the validation set</span></span>
<span id="cb2-14"><a href="#cb2-14" aria-hidden="true" tabindex="-1"></a><span class="bu">print</span>(<span class="st">"Validation set target variable distribution:"</span>)</span>
<span id="cb2-15"><a href="#cb2-15" aria-hidden="true" tabindex="-1"></a><span class="bu">print</span>(y_val_s3.value_counts(normalize<span class="op">=</span><span class="va">True</span>))</span>
<span id="cb2-16"><a href="#cb2-16" aria-hidden="true" tabindex="-1"></a><span class="co"># Check the distribution of the target variable in the test set</span></span>
<span id="cb2-17"><a href="#cb2-17" aria-hidden="true" tabindex="-1"></a><span class="bu">print</span>(<span class="st">"Test set target variable distribution:"</span>)</span>
<span id="cb2-18"><a href="#cb2-18" aria-hidden="true" tabindex="-1"></a><span class="bu">print</span>(y_test_s3.value_counts(normalize<span class="op">=</span><span class="va">True</span>))</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
<div id="3de7a5db" class="cell" data-execution_count="3">
<div class="sourceCode cell-code" id="cb3"><pre class="sourceCode python code-overflow-wrap code-with-copy"><code class="sourceCode python"><span id="cb3-1"><a href="#cb3-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Scale the data S3</span></span>
<span id="cb3-2"><a href="#cb3-2" aria-hidden="true" tabindex="-1"></a>scaler <span class="op">=</span> StandardScaler()</span>
<span id="cb3-3"><a href="#cb3-3" aria-hidden="true" tabindex="-1"></a>X_train_scaled_s3 <span class="op">=</span> scaler.fit_transform(X_train_s3)</span>
<span id="cb3-4"><a href="#cb3-4" aria-hidden="true" tabindex="-1"></a>X_val_scaled_s3 <span class="op">=</span> scaler.transform(X_val_s3)</span>
<span id="cb3-5"><a href="#cb3-5" aria-hidden="true" tabindex="-1"></a>X_test_scaled_s3 <span class="op">=</span> scaler.transform(X_test_s3)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
<p>A comprehensive architecture search evaluated nine baseline configurations spanning 1-3 layers and 16-64 units per layer, systematically exploring model capacity across different complexity levels. Each architecture was implemented as a Sequential model with dense (fully-connected) layers using ReLU activation, dropout regularization (rate=0.2) between layers, and a final softmax output layer for binary classification. Models employed Glorot uniform weight initialization for stable gradient flow and were compiled with the Adam optimizer (learning rate=0.001) and sparse categorical cross-entropy loss appropriate for multi-class formulation of the binary problem.</p>
<p>Training procedures incorporated early stopping callbacks monitoring validation loss with patience=3 epochs, automatically halting training when validation performance plateaued and restoring weights from the best epoch. This prevents overfitting while maximizing learning from available training data. All models trained for maximum 50 epochs with batch size 32, balancing computational efficiency against gradient estimate quality. The deterministic training framework—including seeded batch shuffling—ensures reproducible convergence trajectories across model comparisons.</p>
<p>For hyperparameter optimization, systematic grid search explored learning rates, batch sizes, dropout rates, and L1/L2 regularization strengths, with optimal configurations selected based on validation set ROC-AUC. The tuned models maintained consistent hyperparameter choices (Adam optimizer, learning rate 0.001, dropout 0.2) across stages, with Stage 3 additionally incorporating L1/L2 regularization (0.001 each) to handle the expanded feature space resulting from academic performance metrics.</p>
<div id="b6a40c44" class="cell" data-execution_count="4">
<div class="sourceCode cell-code" id="cb4"><pre class="sourceCode python code-overflow-wrap code-with-copy"><code class="sourceCode python"><span id="cb4-1"><a href="#cb4-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Define Baseline Model</span></span>
<span id="cb4-2"><a href="#cb4-2" aria-hidden="true" tabindex="-1"></a><span class="co"># Suppress TensorFlow warnings and logs</span></span>
<span id="cb4-3"><a href="#cb4-3" aria-hidden="true" tabindex="-1"></a>os.environ[<span class="st">'TF_CPP_MIN_LOG_LEVEL'</span>] <span class="op">=</span> <span class="st">'3'</span>  <span class="co"># Suppress all TF logs (0=all, 1=info, 2=warning, 3=error)</span></span>
<span id="cb4-4"><a href="#cb4-4" aria-hidden="true" tabindex="-1"></a>os.environ[<span class="st">'TF_ENABLE_ONEDNN_OPTS'</span>] <span class="op">=</span> <span class="st">'0'</span>  <span class="co"># Disable oneDNN optimizations warnings</span></span>
<span id="cb4-5"><a href="#cb4-5" aria-hidden="true" tabindex="-1"></a>warnings.filterwarnings(<span class="st">'ignore'</span>)</span>
<span id="cb4-6"><a href="#cb4-6" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb4-7"><a href="#cb4-7" aria-hidden="true" tabindex="-1"></a><span class="co"># Additional TensorFlow logging suppression</span></span>
<span id="cb4-8"><a href="#cb4-8" aria-hidden="true" tabindex="-1"></a>tf.get_logger().setLevel(<span class="st">'ERROR'</span>)</span>
<span id="cb4-9"><a href="#cb4-9" aria-hidden="true" tabindex="-1"></a>tf.autograph.set_verbosity(<span class="dv">0</span>)</span>
<span id="cb4-10"><a href="#cb4-10" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb4-11"><a href="#cb4-11" aria-hidden="true" tabindex="-1"></a><span class="kw">def</span> set_global_determinism(seed<span class="op">=</span><span class="dv">42</span>):</span>
<span id="cb4-12"><a href="#cb4-12" aria-hidden="true" tabindex="-1"></a>    <span class="co">"""</span></span>
<span id="cb4-13"><a href="#cb4-13" aria-hidden="true" tabindex="-1"></a><span class="co">    Enable 100% reproducibility on operations related to tensor and randomness.</span></span>
<span id="cb4-14"><a href="#cb4-14" aria-hidden="true" tabindex="-1"></a><span class="co">    """</span></span>
<span id="cb4-15"><a href="#cb4-15" aria-hidden="true" tabindex="-1"></a>    os.environ[<span class="st">'PYTHONHASHSEED'</span>] <span class="op">=</span> <span class="bu">str</span>(seed)</span>
<span id="cb4-16"><a href="#cb4-16" aria-hidden="true" tabindex="-1"></a>    os.environ[<span class="st">'TF_DETERMINISTIC_OPS'</span>] <span class="op">=</span> <span class="st">'1'</span></span>
<span id="cb4-17"><a href="#cb4-17" aria-hidden="true" tabindex="-1"></a>    os.environ[<span class="st">'TF_CUDNN_DETERMINISTIC'</span>] <span class="op">=</span> <span class="st">'1'</span></span>
<span id="cb4-18"><a href="#cb4-18" aria-hidden="true" tabindex="-1"></a>    </span>
<span id="cb4-19"><a href="#cb4-19" aria-hidden="true" tabindex="-1"></a>    random.seed(seed)</span>
<span id="cb4-20"><a href="#cb4-20" aria-hidden="true" tabindex="-1"></a>    np.random.seed(seed)</span>
<span id="cb4-21"><a href="#cb4-21" aria-hidden="true" tabindex="-1"></a>    tf.random.set_seed(seed)</span>
<span id="cb4-22"><a href="#cb4-22" aria-hidden="true" tabindex="-1"></a>    </span>
<span id="cb4-23"><a href="#cb4-23" aria-hidden="true" tabindex="-1"></a>    <span class="co"># Configure TensorFlow for determinism</span></span>
<span id="cb4-24"><a href="#cb4-24" aria-hidden="true" tabindex="-1"></a>    tf.config.experimental.enable_op_determinism()</span>
<span id="cb4-25"><a href="#cb4-25" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb4-26"><a href="#cb4-26" aria-hidden="true" tabindex="-1"></a><span class="co"># Call this at the very beginning of your script</span></span>
<span id="cb4-27"><a href="#cb4-27" aria-hidden="true" tabindex="-1"></a>set_global_determinism(<span class="dv">42</span>)</span>
<span id="cb4-28"><a href="#cb4-28" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb4-29"><a href="#cb4-29" aria-hidden="true" tabindex="-1"></a><span class="co"># Define Baseline Model with seed reset</span></span>
<span id="cb4-30"><a href="#cb4-30" aria-hidden="true" tabindex="-1"></a><span class="kw">def</span> create_model(input_dim, output_dim, layers<span class="op">=</span><span class="dv">2</span>, units<span class="op">=</span><span class="dv">128</span>, dropout<span class="op">=</span><span class="fl">0.2</span>, lr<span class="op">=</span><span class="fl">0.001</span>, seed<span class="op">=</span><span class="dv">42</span>):</span>
<span id="cb4-31"><a href="#cb4-31" aria-hidden="true" tabindex="-1"></a>    <span class="co"># Reset seeds before each model creation</span></span>
<span id="cb4-32"><a href="#cb4-32" aria-hidden="true" tabindex="-1"></a>    tf.random.set_seed(seed)</span>
<span id="cb4-33"><a href="#cb4-33" aria-hidden="true" tabindex="-1"></a>    np.random.seed(seed)</span>
<span id="cb4-34"><a href="#cb4-34" aria-hidden="true" tabindex="-1"></a>    </span>
<span id="cb4-35"><a href="#cb4-35" aria-hidden="true" tabindex="-1"></a>    model <span class="op">=</span> Sequential(name<span class="op">=</span><span class="ss">f"model_</span><span class="sc">{</span>layers<span class="sc">}</span><span class="ss">L_</span><span class="sc">{</span>units<span class="sc">}</span><span class="ss">U"</span>)</span>
<span id="cb4-36"><a href="#cb4-36" aria-hidden="true" tabindex="-1"></a>    model.add(InputLayer(shape<span class="op">=</span>(input_dim,)))</span>
<span id="cb4-37"><a href="#cb4-37" aria-hidden="true" tabindex="-1"></a>    </span>
<span id="cb4-38"><a href="#cb4-38" aria-hidden="true" tabindex="-1"></a>    <span class="cf">for</span> _ <span class="kw">in</span> <span class="bu">range</span>(layers):</span>
<span id="cb4-39"><a href="#cb4-39" aria-hidden="true" tabindex="-1"></a>        model.add(Dense(units, activation<span class="op">=</span><span class="st">'relu'</span>, </span>
<span id="cb4-40"><a href="#cb4-40" aria-hidden="true" tabindex="-1"></a>                       kernel_initializer<span class="op">=</span>tf.keras.initializers.GlorotUniform(seed<span class="op">=</span>seed),</span>
<span id="cb4-41"><a href="#cb4-41" aria-hidden="true" tabindex="-1"></a>                       bias_initializer<span class="op">=</span>tf.keras.initializers.Zeros()))</span>
<span id="cb4-42"><a href="#cb4-42" aria-hidden="true" tabindex="-1"></a>        model.add(Dropout(dropout, seed<span class="op">=</span>seed))</span>
<span id="cb4-43"><a href="#cb4-43" aria-hidden="true" tabindex="-1"></a>    </span>
<span id="cb4-44"><a href="#cb4-44" aria-hidden="true" tabindex="-1"></a>    model.add(Dense(output_dim, activation<span class="op">=</span><span class="st">'softmax'</span>,</span>
<span id="cb4-45"><a href="#cb4-45" aria-hidden="true" tabindex="-1"></a>                   kernel_initializer<span class="op">=</span>tf.keras.initializers.GlorotUniform(seed<span class="op">=</span>seed),</span>
<span id="cb4-46"><a href="#cb4-46" aria-hidden="true" tabindex="-1"></a>                   bias_initializer<span class="op">=</span>tf.keras.initializers.Zeros()))</span>
<span id="cb4-47"><a href="#cb4-47" aria-hidden="true" tabindex="-1"></a>    </span>
<span id="cb4-48"><a href="#cb4-48" aria-hidden="true" tabindex="-1"></a>    model.<span class="bu">compile</span>(optimizer<span class="op">=</span>Adam(learning_rate<span class="op">=</span>lr),</span>
<span id="cb4-49"><a href="#cb4-49" aria-hidden="true" tabindex="-1"></a>                 loss<span class="op">=</span><span class="st">'sparse_categorical_crossentropy'</span>,</span>
<span id="cb4-50"><a href="#cb4-50" aria-hidden="true" tabindex="-1"></a>                 metrics<span class="op">=</span>[<span class="st">'accuracy'</span>])</span>
<span id="cb4-51"><a href="#cb4-51" aria-hidden="true" tabindex="-1"></a>    <span class="cf">return</span> model</span>
<span id="cb4-52"><a href="#cb4-52" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb4-53"><a href="#cb4-53" aria-hidden="true" tabindex="-1"></a><span class="co"># Training setup with deterministic seeds</span></span>
<span id="cb4-54"><a href="#cb4-54" aria-hidden="true" tabindex="-1"></a><span class="kw">def</span> train_models_deterministic(architecture_configs, X_train, y_train, X_val, y_val):</span>
<span id="cb4-55"><a href="#cb4-55" aria-hidden="true" tabindex="-1"></a>    models_base_s3 <span class="op">=</span> []</span>
<span id="cb4-56"><a href="#cb4-56" aria-hidden="true" tabindex="-1"></a>    histories_base_s3 <span class="op">=</span> []</span>
<span id="cb4-57"><a href="#cb4-57" aria-hidden="true" tabindex="-1"></a>    </span>
<span id="cb4-58"><a href="#cb4-58" aria-hidden="true" tabindex="-1"></a>    <span class="cf">for</span> i, config <span class="kw">in</span> <span class="bu">enumerate</span>(architecture_configs):</span>
<span id="cb4-59"><a href="#cb4-59" aria-hidden="true" tabindex="-1"></a>        <span class="bu">print</span>(<span class="ss">f"</span><span class="ch">\n</span><span class="ss">Training Model </span><span class="sc">{</span>i<span class="op">+</span><span class="dv">1</span><span class="sc">}</span><span class="ss">: </span><span class="sc">{</span>config<span class="sc">}</span><span class="ss">"</span>)</span>
<span id="cb4-60"><a href="#cb4-60" aria-hidden="true" tabindex="-1"></a>        </span>
<span id="cb4-61"><a href="#cb4-61" aria-hidden="true" tabindex="-1"></a>        <span class="co"># Set unique but deterministic seed for each model</span></span>
<span id="cb4-62"><a href="#cb4-62" aria-hidden="true" tabindex="-1"></a>        model_seed <span class="op">=</span> <span class="dv">42</span> <span class="op">+</span> i</span>
<span id="cb4-63"><a href="#cb4-63" aria-hidden="true" tabindex="-1"></a>        set_global_determinism(model_seed)</span>
<span id="cb4-64"><a href="#cb4-64" aria-hidden="true" tabindex="-1"></a>        </span>
<span id="cb4-65"><a href="#cb4-65" aria-hidden="true" tabindex="-1"></a>        <span class="co"># Clear session</span></span>
<span id="cb4-66"><a href="#cb4-66" aria-hidden="true" tabindex="-1"></a>        tf.keras.backend.clear_session()</span>
<span id="cb4-67"><a href="#cb4-67" aria-hidden="true" tabindex="-1"></a>        gc.collect()</span>
<span id="cb4-68"><a href="#cb4-68" aria-hidden="true" tabindex="-1"></a>        </span>
<span id="cb4-69"><a href="#cb4-69" aria-hidden="true" tabindex="-1"></a>        <span class="co"># Create model with specific seed</span></span>
<span id="cb4-70"><a href="#cb4-70" aria-hidden="true" tabindex="-1"></a>        model <span class="op">=</span> create_model(input_dim, output_dim, seed<span class="op">=</span>model_seed, <span class="op">**</span>config)</span>
<span id="cb4-71"><a href="#cb4-71" aria-hidden="true" tabindex="-1"></a>        </span>
<span id="cb4-72"><a href="#cb4-72" aria-hidden="true" tabindex="-1"></a>        <span class="co"># Early stopping</span></span>
<span id="cb4-73"><a href="#cb4-73" aria-hidden="true" tabindex="-1"></a>        early_stop <span class="op">=</span> EarlyStopping(monitor<span class="op">=</span><span class="st">'val_loss'</span>, patience<span class="op">=</span><span class="dv">3</span>, </span>
<span id="cb4-74"><a href="#cb4-74" aria-hidden="true" tabindex="-1"></a>                                 restore_best_weights<span class="op">=</span><span class="va">True</span>)</span>
<span id="cb4-75"><a href="#cb4-75" aria-hidden="true" tabindex="-1"></a>        </span>
<span id="cb4-76"><a href="#cb4-76" aria-hidden="true" tabindex="-1"></a>        <span class="co"># Train with deterministic batch shuffling</span></span>
<span id="cb4-77"><a href="#cb4-77" aria-hidden="true" tabindex="-1"></a>        history <span class="op">=</span> model.fit(X_train, y_train,</span>
<span id="cb4-78"><a href="#cb4-78" aria-hidden="true" tabindex="-1"></a>                          validation_data<span class="op">=</span>(X_val, y_val),</span>
<span id="cb4-79"><a href="#cb4-79" aria-hidden="true" tabindex="-1"></a>                          batch_size<span class="op">=</span><span class="dv">32</span>,</span>
<span id="cb4-80"><a href="#cb4-80" aria-hidden="true" tabindex="-1"></a>                          epochs<span class="op">=</span><span class="dv">50</span>,</span>
<span id="cb4-81"><a href="#cb4-81" aria-hidden="true" tabindex="-1"></a>                          callbacks<span class="op">=</span>[early_stop],</span>
<span id="cb4-82"><a href="#cb4-82" aria-hidden="true" tabindex="-1"></a>                          shuffle<span class="op">=</span><span class="va">True</span>,  <span class="co"># This will be deterministic due to seed</span></span>
<span id="cb4-83"><a href="#cb4-83" aria-hidden="true" tabindex="-1"></a>                          verbose<span class="op">=</span><span class="dv">0</span>)</span>
<span id="cb4-84"><a href="#cb4-84" aria-hidden="true" tabindex="-1"></a>        </span>
<span id="cb4-85"><a href="#cb4-85" aria-hidden="true" tabindex="-1"></a>        <span class="co"># Evaluate</span></span>
<span id="cb4-86"><a href="#cb4-86" aria-hidden="true" tabindex="-1"></a>        train_loss, train_accuracy <span class="op">=</span> model.evaluate(X_train, y_train, verbose<span class="op">=</span><span class="dv">0</span>)</span>
<span id="cb4-87"><a href="#cb4-87" aria-hidden="true" tabindex="-1"></a>        val_loss, val_acc <span class="op">=</span> model.evaluate(X_val, y_val, verbose<span class="op">=</span><span class="dv">0</span>)</span>
<span id="cb4-88"><a href="#cb4-88" aria-hidden="true" tabindex="-1"></a>        </span>
<span id="cb4-89"><a href="#cb4-89" aria-hidden="true" tabindex="-1"></a>        <span class="co"># Store results</span></span>
<span id="cb4-90"><a href="#cb4-90" aria-hidden="true" tabindex="-1"></a>        models_base_s3.append(model)</span>
<span id="cb4-91"><a href="#cb4-91" aria-hidden="true" tabindex="-1"></a>        histories_base_s3.append({</span>
<span id="cb4-92"><a href="#cb4-92" aria-hidden="true" tabindex="-1"></a>            <span class="st">"config"</span>: config,</span>
<span id="cb4-93"><a href="#cb4-93" aria-hidden="true" tabindex="-1"></a>            <span class="st">"train_loss"</span>: train_loss,</span>
<span id="cb4-94"><a href="#cb4-94" aria-hidden="true" tabindex="-1"></a>            <span class="st">"train_accuracy"</span>: train_accuracy,</span>
<span id="cb4-95"><a href="#cb4-95" aria-hidden="true" tabindex="-1"></a>            <span class="st">"val_loss"</span>: val_loss,</span>
<span id="cb4-96"><a href="#cb4-96" aria-hidden="true" tabindex="-1"></a>            <span class="st">"val_accuracy"</span>: val_acc,</span>
<span id="cb4-97"><a href="#cb4-97" aria-hidden="true" tabindex="-1"></a>            <span class="st">"history"</span>: history,</span>
<span id="cb4-98"><a href="#cb4-98" aria-hidden="true" tabindex="-1"></a>            <span class="st">"seed"</span>: model_seed</span>
<span id="cb4-99"><a href="#cb4-99" aria-hidden="true" tabindex="-1"></a>        })</span>
<span id="cb4-100"><a href="#cb4-100" aria-hidden="true" tabindex="-1"></a>        </span>
<span id="cb4-101"><a href="#cb4-101" aria-hidden="true" tabindex="-1"></a>        <span class="bu">print</span>(<span class="ss">f"Final validation accuracy: </span><span class="sc">{</span>val_acc<span class="sc">:.4f}</span><span class="ss">"</span>)</span>
<span id="cb4-102"><a href="#cb4-102" aria-hidden="true" tabindex="-1"></a>        gc.collect()</span>
<span id="cb4-103"><a href="#cb4-103" aria-hidden="true" tabindex="-1"></a>    </span>
<span id="cb4-104"><a href="#cb4-104" aria-hidden="true" tabindex="-1"></a>    <span class="cf">return</span> models_base_s3, histories_base_s3</span>
<span id="cb4-105"><a href="#cb4-105" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb4-106"><a href="#cb4-106" aria-hidden="true" tabindex="-1"></a><span class="co"># Usage</span></span>
<span id="cb4-107"><a href="#cb4-107" aria-hidden="true" tabindex="-1"></a>set_global_determinism(<span class="dv">42</span>)  <span class="co"># Set at the beginning</span></span>
<span id="cb4-108"><a href="#cb4-108" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb4-109"><a href="#cb4-109" aria-hidden="true" tabindex="-1"></a><span class="co"># Get dimensions</span></span>
<span id="cb4-110"><a href="#cb4-110" aria-hidden="true" tabindex="-1"></a>input_dim <span class="op">=</span> X_train_scaled_s3.shape[<span class="dv">1</span>]</span>
<span id="cb4-111"><a href="#cb4-111" aria-hidden="true" tabindex="-1"></a>output_dim <span class="op">=</span> <span class="bu">len</span>(np.unique(y_train_s3))</span>
<span id="cb4-112"><a href="#cb4-112" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb4-113"><a href="#cb4-113" aria-hidden="true" tabindex="-1"></a><span class="co"># Architecture configurations</span></span>
<span id="cb4-114"><a href="#cb4-114" aria-hidden="true" tabindex="-1"></a>architecture_configs <span class="op">=</span> [</span>
<span id="cb4-115"><a href="#cb4-115" aria-hidden="true" tabindex="-1"></a>    {<span class="st">"layers"</span>: <span class="dv">1</span>, <span class="st">"units"</span>: <span class="dv">16</span>},</span>
<span id="cb4-116"><a href="#cb4-116" aria-hidden="true" tabindex="-1"></a>    {<span class="st">"layers"</span>: <span class="dv">1</span>, <span class="st">"units"</span>: <span class="dv">32</span>},</span>
<span id="cb4-117"><a href="#cb4-117" aria-hidden="true" tabindex="-1"></a>    {<span class="st">"layers"</span>: <span class="dv">1</span>, <span class="st">"units"</span>: <span class="dv">64</span>},</span>
<span id="cb4-118"><a href="#cb4-118" aria-hidden="true" tabindex="-1"></a>    {<span class="st">"layers"</span>: <span class="dv">2</span>, <span class="st">"units"</span>: <span class="dv">16</span>},</span>
<span id="cb4-119"><a href="#cb4-119" aria-hidden="true" tabindex="-1"></a>    {<span class="st">"layers"</span>: <span class="dv">2</span>, <span class="st">"units"</span>: <span class="dv">32</span>},</span>
<span id="cb4-120"><a href="#cb4-120" aria-hidden="true" tabindex="-1"></a>    {<span class="st">"layers"</span>: <span class="dv">2</span>, <span class="st">"units"</span>: <span class="dv">64</span>},</span>
<span id="cb4-121"><a href="#cb4-121" aria-hidden="true" tabindex="-1"></a>    {<span class="st">"layers"</span>: <span class="dv">3</span>, <span class="st">"units"</span>: <span class="dv">16</span>},</span>
<span id="cb4-122"><a href="#cb4-122" aria-hidden="true" tabindex="-1"></a>    {<span class="st">"layers"</span>: <span class="dv">3</span>, <span class="st">"units"</span>: <span class="dv">32</span>},</span>
<span id="cb4-123"><a href="#cb4-123" aria-hidden="true" tabindex="-1"></a>    {<span class="st">"layers"</span>: <span class="dv">3</span>, <span class="st">"units"</span>: <span class="dv">64</span>}</span>
<span id="cb4-124"><a href="#cb4-124" aria-hidden="true" tabindex="-1"></a>]</span>
<span id="cb4-125"><a href="#cb4-125" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb4-126"><a href="#cb4-126" aria-hidden="true" tabindex="-1"></a><span class="co"># Train models deterministically</span></span>
<span id="cb4-127"><a href="#cb4-127" aria-hidden="true" tabindex="-1"></a>models_base_s3, histories_base_s3 <span class="op">=</span> train_models_deterministic(architecture_configs, X_train_scaled_s3, y_train_s3, X_val_scaled_s3, y_val_s3)</span>
<span id="cb4-128"><a href="#cb4-128" aria-hidden="true" tabindex="-1"></a><span class="bu">print</span>(<span class="ss">f'Model: models_base_s3, History:histories_base_s3'</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
</section>
<section id="evaluation-strategy" class="level3">
<h3 class="anchored" data-anchor-id="evaluation-strategy">Evaluation Strategy</h3>
<p>Model performance was assessed using multiple metrics appropriate for imbalanced classification: ROC-AUC (discrimination ability across classification thresholds), F1-score (harmonic mean of precision and recall), precision (proportion of predicted dropouts that were actual dropouts), and recall (proportion of actual dropouts correctly identified). These metrics provide complementary views of model performance, with particular emphasis on recall given the institutional priority of identifying at-risk students even at the cost of some false positives.</p>
<p>Comparative analysis evaluated both base model configurations and hyperparameter-tuned variants across all three data stages, enabling assessment of how model performance evolves with progressive data enrichment and systematic optimization.</p>
</section>
</section>
<section id="results" class="level2">
<h2 class="anchored" data-anchor-id="results">Results</h2>
<section id="training-dynamics-of-stage-3-baseline-models" class="level3">
<h3 class="anchored" data-anchor-id="training-dynamics-of-stage-3-baseline-models">Training Dynamics of Stage 3 Baseline Models</h3>
<div class="cell" data-execution_count="5" data-tbl-cap-location="bottom">
<div id="tbl-1" class="cell quarto-float quarto-figure quarto-figure-center anchored" data-tbl-cap-location="bottom" data-execution_count="5">
<figure class="quarto-float quarto-float-tbl figure">
<div aria-describedby="tbl-1-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
<div class="cell-output cell-output-display">
<div>


<table class="dataframe do-not-create-environment cell caption-top table table-sm table-striped small" data-quarto-postprocess="true" data-border="1">
<thead>
<tr class="header">
<th data-quarto-table-cell-role="th"></th>
<th data-quarto-table-cell-role="th">Model</th>
<th data-quarto-table-cell-role="th">Stage</th>
<th data-quarto-table-cell-role="th">Hyperparameters</th>
<th data-quarto-table-cell-role="th">ROC-AUC</th>
<th data-quarto-table-cell-role="th">F1</th>
<th data-quarto-table-cell-role="th">Precision</th>
<th data-quarto-table-cell-role="th">Recall</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td data-quarto-table-cell-role="th">0</td>
<td>Base</td>
<td>1</td>
<td>Model_6_4L_64U</td>
<td>0.854301</td>
<td>0.928876</td>
<td>0.897225</td>
<td>0.962843</td>
</tr>
<tr class="even">
<td data-quarto-table-cell-role="th">1</td>
<td>Tuned</td>
<td>1</td>
<td>Model_7_adamO_16BS_0.001LR_0.2D</td>
<td>0.852630</td>
<td>0.929038</td>
<td>0.895486</td>
<td>0.965202</td>
</tr>
<tr class="odd">
<td data-quarto-table-cell-role="th">2</td>
<td>Base</td>
<td>2</td>
<td>Model_1_2L_32U</td>
<td>0.886575</td>
<td>0.936731</td>
<td>0.909900</td>
<td>0.965192</td>
</tr>
<tr class="even">
<td data-quarto-table-cell-role="th">3</td>
<td>Tuned</td>
<td>2</td>
<td>Model_7_adamO_16BS_0.001LR_0.2D</td>
<td>0.887617</td>
<td>0.938959</td>
<td>0.923296</td>
<td>0.955162</td>
</tr>
<tr class="odd">
<td data-quarto-table-cell-role="th">4</td>
<td>Base</td>
<td>3</td>
<td>Model_5_2L_32U</td>
<td>0.984586</td>
<td>0.972354</td>
<td>0.979928</td>
<td>0.964897</td>
</tr>
<tr class="even">
<td data-quarto-table-cell-role="th">5</td>
<td>Tuned</td>
<td>3</td>
<td>do:0.2 lr:0.001 opt:adam bs:32 L1:0.001 L2:0.001</td>
<td>0.983790</td>
<td>0.972027</td>
<td>0.986039</td>
<td>0.958407</td>
</tr>
</tbody>
</table>

</div>
</div>
</div>
<figcaption class="quarto-float-caption-bottom quarto-float-caption quarto-float-tbl" id="tbl-1-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
Table&nbsp;1: Performance comparison of neural network architectures across three data stages
</figcaption>
</figure>
</div>
</div>
<p>Table 1 demonstrates progressive performance improvement across three data stages, with Stage 3 (end-of-semester data) achieving substantially higher discrimination capability than earlier stages. For Stage 1, base and tuned models achieve similar ROC-AUC scores (0.854 vs.&nbsp;0.853) and F1-scores (0.929 for both), indicating limited benefit from hyperparameter optimization when only demographic and enrollment features are available. Stage 2 performance shows modest improvement, with ROC-AUC increasing to 0.887 (base) and 0.888 (tuned), though hyperparameter tuning again yields minimal gains.</p>
<p>The most striking pattern emerges in Stage 3, where both models achieve exceptional performance with ROC-AUC exceeding 0.98 and F1-scores of 0.972. The base Stage 3 model (ROC-AUC: 0.9846, F1: 0.972, Precision: 0.980, Recall: 0.965) demonstrates that comprehensive end-of-semester data enables highly accurate dropout prediction even without extensive tuning. The tuned Stage 3 model shows nearly identical performance (ROC-AUC: 0.9838, F1: 0.972), with marginally higher precision (0.986) but slightly lower recall (0.958). These results indicate that data richness, incorporating final grades and module completion rates, far outweighs architectural optimization for this prediction task. The 13-14 percentage point improvement in ROC-AUC from Stage 1 to Stage 3 quantifies the value of comprehensive academic performance data for early warning system effectiveness.</p>
<p>An important methodological consideration: the models compared across stages do not share identical architectures or hyperparameter configurations. Each stage’s models were independently optimized for their respective feature sets through systematic hyperparameter search, with the best-performing configuration selected based on validation performance. Notably, the optimal architectures show counterintuitive patterns: Stage 1 base model employed a deeper 4-layer architecture with 64 units (Model_6_4L_64U), while Stages 2 and 3 base models utilized simpler 2-layer architectures with 32 units (Model_1_2L_32U and Model_5_2L_32U respectively). This suggests that with limited predictive signal from demographic features alone (Stage 1), models required additional architectural capacity to extract weak patterns, whereas data-rich stages (2 and 3) enabled simpler architectures to achieve superior performance through stronger feature-outcome relationships. The tuned models across all stages employed consistent hyperparameter configurations (Adam optimizer, learning rate 0.001, dropout 0.2, batch size 16-32), with Stage 3 additionally incorporating L1/L2 regularization (0.001 each) to prevent overfitting on the expanded feature space. These results suggest that optimal model complexity does not necessarily scale with data richness, and that more powerful features can enable simpler, more efficient architectures that outperform complex models trained on weak signals.</p>
<div id="5bfcfea1" class="cell" data-execution_count="6">
<div class="sourceCode cell-code" id="cb5"><pre class="sourceCode python code-overflow-wrap code-with-copy"><code class="sourceCode python"><span id="cb5-1"><a href="#cb5-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Plot train/validation accuracy.</span></span>
<span id="cb5-2"><a href="#cb5-2" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb5-3"><a href="#cb5-3" aria-hidden="true" tabindex="-1"></a>plt.figure(figsize<span class="op">=</span>(<span class="dv">12</span>, <span class="dv">6</span>))</span>
<span id="cb5-4"><a href="#cb5-4" aria-hidden="true" tabindex="-1"></a><span class="cf">for</span> i, result <span class="kw">in</span> <span class="bu">enumerate</span>(histories_base_s3):</span>
<span id="cb5-5"><a href="#cb5-5" aria-hidden="true" tabindex="-1"></a>    config <span class="op">=</span> result[<span class="st">'config'</span>]</span>
<span id="cb5-6"><a href="#cb5-6" aria-hidden="true" tabindex="-1"></a>    config_str <span class="op">=</span> <span class="ss">f"Layers: </span><span class="sc">{</span>config[<span class="st">'layers'</span>]<span class="sc">}</span><span class="ss">, Units: </span><span class="sc">{</span>config[<span class="st">'units'</span>]<span class="sc">}</span><span class="ss">"</span></span>
<span id="cb5-7"><a href="#cb5-7" aria-hidden="true" tabindex="-1"></a>    history_obj <span class="op">=</span> result[<span class="st">'history'</span>]</span>
<span id="cb5-8"><a href="#cb5-8" aria-hidden="true" tabindex="-1"></a>    </span>
<span id="cb5-9"><a href="#cb5-9" aria-hidden="true" tabindex="-1"></a>    plt.plot(history_obj.history[<span class="st">'accuracy'</span>], label<span class="op">=</span><span class="ss">f"Train Acc - </span><span class="sc">{</span>config_str<span class="sc">}</span><span class="ss">"</span>)</span>
<span id="cb5-10"><a href="#cb5-10" aria-hidden="true" tabindex="-1"></a>    plt.plot(history_obj.history[<span class="st">'val_accuracy'</span>], linestyle<span class="op">=</span><span class="st">'--'</span>, label<span class="op">=</span><span class="ss">f"Val Acc - </span><span class="sc">{</span>config_str<span class="sc">}</span><span class="ss">"</span>)</span>
<span id="cb5-11"><a href="#cb5-11" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb5-12"><a href="#cb5-12" aria-hidden="true" tabindex="-1"></a>plt.title(<span class="st">'Training and Validation Accuracy Comparison'</span>)</span>
<span id="cb5-13"><a href="#cb5-13" aria-hidden="true" tabindex="-1"></a>plt.xlabel(<span class="st">'Epochs'</span>)</span>
<span id="cb5-14"><a href="#cb5-14" aria-hidden="true" tabindex="-1"></a>plt.ylabel(<span class="st">'Accuracy'</span>)</span>
<span id="cb5-15"><a href="#cb5-15" aria-hidden="true" tabindex="-1"></a>plt.legend()</span>
<span id="cb5-16"><a href="#cb5-16" aria-hidden="true" tabindex="-1"></a>plt.grid(<span class="va">True</span>)</span>
<span id="cb5-17"><a href="#cb5-17" aria-hidden="true" tabindex="-1"></a>plt.show()</span>
<span id="cb5-18"><a href="#cb5-18" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb5-19"><a href="#cb5-19" aria-hidden="true" tabindex="-1"></a><span class="co"># Plot train/validation loss</span></span>
<span id="cb5-20"><a href="#cb5-20" aria-hidden="true" tabindex="-1"></a>plt.figure(figsize<span class="op">=</span>(<span class="dv">12</span>, <span class="dv">6</span>))</span>
<span id="cb5-21"><a href="#cb5-21" aria-hidden="true" tabindex="-1"></a><span class="cf">for</span> i, result <span class="kw">in</span> <span class="bu">enumerate</span>(histories_base_s3):</span>
<span id="cb5-22"><a href="#cb5-22" aria-hidden="true" tabindex="-1"></a>    config <span class="op">=</span> result[<span class="st">'config'</span>]</span>
<span id="cb5-23"><a href="#cb5-23" aria-hidden="true" tabindex="-1"></a>    config_str <span class="op">=</span> <span class="ss">f"Layers: </span><span class="sc">{</span>config[<span class="st">'layers'</span>]<span class="sc">}</span><span class="ss">, Units: </span><span class="sc">{</span>config[<span class="st">'units'</span>]<span class="sc">}</span><span class="ss">"</span></span>
<span id="cb5-24"><a href="#cb5-24" aria-hidden="true" tabindex="-1"></a>    history_obj <span class="op">=</span> result[<span class="st">'history'</span>]</span>
<span id="cb5-25"><a href="#cb5-25" aria-hidden="true" tabindex="-1"></a>    </span>
<span id="cb5-26"><a href="#cb5-26" aria-hidden="true" tabindex="-1"></a>    plt.plot(history_obj.history[<span class="st">'loss'</span>], label<span class="op">=</span><span class="ss">f"Train Loss - </span><span class="sc">{</span>config_str<span class="sc">}</span><span class="ss">"</span>)</span>
<span id="cb5-27"><a href="#cb5-27" aria-hidden="true" tabindex="-1"></a>    plt.plot(history_obj.history[<span class="st">'val_loss'</span>], linestyle<span class="op">=</span><span class="st">'--'</span>, label<span class="op">=</span><span class="ss">f"Val Loss - </span><span class="sc">{</span>config_str<span class="sc">}</span><span class="ss">"</span>)</span>
<span id="cb5-28"><a href="#cb5-28" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb5-29"><a href="#cb5-29" aria-hidden="true" tabindex="-1"></a>plt.title(<span class="st">'Training and Validation Loss Comparison'</span>)</span>
<span id="cb5-30"><a href="#cb5-30" aria-hidden="true" tabindex="-1"></a>plt.xlabel(<span class="st">'Epochs'</span>)</span>
<span id="cb5-31"><a href="#cb5-31" aria-hidden="true" tabindex="-1"></a>plt.ylabel(<span class="st">'Loss'</span>)</span>
<span id="cb5-32"><a href="#cb5-32" aria-hidden="true" tabindex="-1"></a>plt.legend()</span>
<span id="cb5-33"><a href="#cb5-33" aria-hidden="true" tabindex="-1"></a>plt.grid(<span class="va">True</span>)</span>
<span id="cb5-34"><a href="#cb5-34" aria-hidden="true" tabindex="-1"></a>plt.show()</span>
<span id="cb5-35"><a href="#cb5-35" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb5-36"><a href="#cb5-36" aria-hidden="true" tabindex="-1"></a><span class="co"># Print numerical summary</span></span>
<span id="cb5-37"><a href="#cb5-37" aria-hidden="true" tabindex="-1"></a><span class="bu">print</span>(<span class="st">"</span><span class="ch">\n</span><span class="st">Model Performance Summary:"</span>)</span>
<span id="cb5-38"><a href="#cb5-38" aria-hidden="true" tabindex="-1"></a><span class="bu">print</span>(<span class="st">"="</span> <span class="op">*</span> <span class="dv">60</span>)</span>
<span id="cb5-39"><a href="#cb5-39" aria-hidden="true" tabindex="-1"></a><span class="cf">for</span> i, result <span class="kw">in</span> <span class="bu">enumerate</span>(histories_base_s3):</span>
<span id="cb5-40"><a href="#cb5-40" aria-hidden="true" tabindex="-1"></a>    config <span class="op">=</span> result[<span class="st">'config'</span>]</span>
<span id="cb5-41"><a href="#cb5-41" aria-hidden="true" tabindex="-1"></a>    <span class="bu">print</span>(<span class="ss">f"Model </span><span class="sc">{</span>i<span class="op">+</span><span class="dv">1</span><span class="sc">}</span><span class="ss"> - </span><span class="sc">{</span>config[<span class="st">'layers'</span>]<span class="sc">}</span><span class="ss"> layers, </span><span class="sc">{</span>config[<span class="st">'units'</span>]<span class="sc">}</span><span class="ss"> units:"</span>)</span>
<span id="cb5-42"><a href="#cb5-42" aria-hidden="true" tabindex="-1"></a>    <span class="bu">print</span>(<span class="ss">f"  Validation Accuracy: </span><span class="sc">{</span>result[<span class="st">'val_accuracy'</span>]<span class="sc">:.4f}</span><span class="ss">"</span>)</span>
<span id="cb5-43"><a href="#cb5-43" aria-hidden="true" tabindex="-1"></a>    <span class="bu">print</span>(<span class="ss">f"  Final Epochs: </span><span class="sc">{</span><span class="bu">len</span>(result[<span class="st">'history'</span>].history[<span class="st">'loss'</span>])<span class="sc">}</span><span class="ss">"</span>)</span>
<span id="cb5-44"><a href="#cb5-44" aria-hidden="true" tabindex="-1"></a>    <span class="bu">print</span>()</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
<figure id="fig-1" class="figure">
  <div style="text-align: center; margin-bottom: 1rem;">
    <div style="font-size: 20pt; font-weight: normal; color: #2c3e50;">Learning Curves Matrix</div>
  </div>
  <div style="display: flex; gap: 1.5rem; justify-content: center; flex-wrap: wrap;">
    <img src="../assets/student_dropout/figures/val_accuracy_curve_s3_nn.png" style="width: 40%; min-width: 300px;" alt="Validation accuracy curves" class="figure-img">
    <img src="../assets/student_dropout/figures/learning_curve_nn_s3.png" style="width: 40%; min-width: 300px;" alt="Training and validation loss" class="figure-img">
  </div>
  <figcaption>Figure 1: Neural network training dynamics showing validation accuracy progression and loss convergence</figcaption>
</figure>
<p>Figure 1 illustrates neural network training dynamics for Stage 3 models across the nine baseline architectures evaluated during systematic architecture search. The left panel shows validation accuracy curves demonstrating rapid convergence within early epochs, with models achieving &gt;90% accuracy before epoch 10. Different model configurations (varying from 1-3 layers and 16-64 units) show distinct convergence patterns, though all reach similar final performance plateaus around 94-95% validation accuracy. The right panel displays training and validation loss curves, revealing typical deep learning behavior where training loss continues decreasing while validation loss stabilizes, indicating the point where further training risks overfitting. The modest gap between training and validation curves suggests effective regularization through dropout (rate=0.2). Early stopping callbacks with patience=3 epochs triggered early in training, most models converged within 6-10 epochs, reflecting the strong predictive signal in Stage 3 academic performance features that enabled rapid learning and prevented unnecessary computation. These dynamics validate the training procedure’s effectiveness: models achieved strong generalization performance efficiently, without requiring extensive training or exhibiting severe overfitting, demonstrating that rich feature sets enable both superior performance and faster convergence.</p>
</section>
<section id="detailed-model-metrics-for-baseline-architectures" class="level3">
<h3 class="anchored" data-anchor-id="detailed-model-metrics-for-baseline-architectures">Detailed Model Metrics for Baseline Architectures</h3>
<div class="cell" data-execution_count="7" data-tbl-cap-location="bottom">
<div id="tbl-2" class="cell quarto-float quarto-figure quarto-figure-center anchored" data-tbl-cap-location="bottom" data-execution_count="7">
<figure class="quarto-float quarto-float-tbl figure">
<div aria-describedby="tbl-2-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
<div class="cell-output cell-output-display">
<div>


<table class="dataframe do-not-create-environment cell caption-top table table-sm table-striped small" data-quarto-postprocess="true" data-border="1">
<thead>
<tr class="header">
<th data-quarto-table-cell-role="th"></th>
<th data-quarto-table-cell-role="th">Model</th>
<th data-quarto-table-cell-role="th">ROC_AUC</th>
<th data-quarto-table-cell-role="th">ROC_AUC_Manual</th>
<th data-quarto-table-cell-role="th">PR_AUC</th>
<th data-quarto-table-cell-role="th">F1</th>
<th data-quarto-table-cell-role="th">Bal_Acc</th>
<th data-quarto-table-cell-role="th">MCC</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td data-quarto-table-cell-role="th">0</td>
<td>Model_5_2L_32U</td>
<td>0.9846</td>
<td>0.9846</td>
<td>0.9973</td>
<td>0.9724</td>
<td>0.9253</td>
<td>0.8215</td>
</tr>
<tr class="even">
<td data-quarto-table-cell-role="th">1</td>
<td>Model_8_3L_32U</td>
<td>0.9838</td>
<td>0.9838</td>
<td>0.9971</td>
<td>0.9707</td>
<td>0.9465</td>
<td>0.8262</td>
</tr>
<tr class="odd">
<td data-quarto-table-cell-role="th">2</td>
<td>Model_2_1L_32U</td>
<td>0.9830</td>
<td>0.9830</td>
<td>0.9971</td>
<td>0.9704</td>
<td>0.9212</td>
<td>0.8101</td>
</tr>
<tr class="even">
<td data-quarto-table-cell-role="th">3</td>
<td>Model_6_2L_64U</td>
<td>0.9830</td>
<td>0.9830</td>
<td>0.9970</td>
<td>0.9699</td>
<td>0.9236</td>
<td>0.8092</td>
</tr>
<tr class="odd">
<td data-quarto-table-cell-role="th">4</td>
<td>Model_3_1L_64U</td>
<td>0.9818</td>
<td>0.9818</td>
<td>0.9967</td>
<td>0.9712</td>
<td>0.9206</td>
<td>0.8134</td>
</tr>
<tr class="even">
<td data-quarto-table-cell-role="th">5</td>
<td>Model_1_1L_16U</td>
<td>0.9814</td>
<td>0.9814</td>
<td>0.9968</td>
<td>0.9708</td>
<td>0.9166</td>
<td>0.8094</td>
</tr>
<tr class="odd">
<td data-quarto-table-cell-role="th">6</td>
<td>Model_9_3L_64U</td>
<td>0.9811</td>
<td>0.9811</td>
<td>0.9967</td>
<td>0.9678</td>
<td>0.9367</td>
<td>0.8084</td>
</tr>
<tr class="even">
<td data-quarto-table-cell-role="th">7</td>
<td>Model_4_2L_16U</td>
<td>0.9802</td>
<td>0.9802</td>
<td>0.9966</td>
<td>0.9697</td>
<td>0.9427</td>
<td>0.8195</td>
</tr>
<tr class="odd">
<td data-quarto-table-cell-role="th">8</td>
<td>Model_7_3L_16U</td>
<td>0.9778</td>
<td>0.9778</td>
<td>0.9959</td>
<td>0.9675</td>
<td>0.9306</td>
<td>0.8029</td>
</tr>
</tbody>
</table>

</div>
</div>
</div>
<figcaption class="quarto-float-caption-bottom quarto-float-caption quarto-float-tbl" id="tbl-2-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
Table&nbsp;2: Detailed evaluation metrics for baseline neural network models
</figcaption>
</figure>
</div>
</div>
<p>Table 2 provides comprehensive evaluation metrics for the nine baseline Stage 3 model architectures from the systematic architecture search visualized in Figure 1. Each row represents one of the configurations spanning 1-3 layers and 16-64 units, evaluated on multiple complementary performance metrics: ROC-AUC (area under receiver operating characteristic curve), PR-AUC (precision-recall curve area), F1-score (harmonic mean of precision and recall), Balanced Accuracy (accounting for class imbalance), and Matthews Correlation Coefficient (MCC, overall classification quality). All nine architectures achieve exceptional performance (ROC-AUC &gt;0.977, F1 &gt;0.967), with remarkably narrow performance variance (ROC-AUC range: 0.9778-0.9846, span of only 0.007). The best-performing model (Model_5_2L_32U: 2 layers, 32 units) achieves ROC-AUC=0.9846, demonstrating that relatively simple architectures can excel given strong feature sets. The tight performance clustering across diverse architectures, from shallow 1-layer networks to deeper 3-layer configurations, validates the conclusion that Stage 3’s rich academic performance features enable robust prediction regardless of architectural complexity. This homogeneity suggests practitioners can prioritize computational efficiency (simpler models) over architectural optimization when working with high-quality features, as the data quality dominates model complexity in determining final performance. The comprehensive metric set enables evidence-based model selection considering multiple evaluation criteria beyond single-metric optimization.</p>
<div id="cd91cbae" class="cell" data-execution_count="8">
<div class="sourceCode cell-code" id="cb6"><pre class="sourceCode python code-overflow-wrap code-with-copy"><code class="sourceCode python"><span id="cb6-1"><a href="#cb6-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Display all the Baseline Models Tested</span></span>
<span id="cb6-2"><a href="#cb6-2" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb6-3"><a href="#cb6-3" aria-hidden="true" tabindex="-1"></a>fig, axes <span class="op">=</span> plt.subplots(<span class="dv">3</span>, <span class="dv">3</span>, figsize<span class="op">=</span>(<span class="dv">10</span>, <span class="dv">10</span>))</span>
<span id="cb6-4"><a href="#cb6-4" aria-hidden="true" tabindex="-1"></a>fig.tight_layout(pad<span class="op">=</span><span class="fl">4.0</span>)</span>
<span id="cb6-5"><a href="#cb6-5" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb6-6"><a href="#cb6-6" aria-hidden="true" tabindex="-1"></a><span class="co"># Flatten the axes array for easier iteration</span></span>
<span id="cb6-7"><a href="#cb6-7" aria-hidden="true" tabindex="-1"></a>axes <span class="op">=</span> axes.ravel()</span>
<span id="cb6-8"><a href="#cb6-8" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb6-9"><a href="#cb6-9" aria-hidden="true" tabindex="-1"></a><span class="co"># Counter for the current subplot</span></span>
<span id="cb6-10"><a href="#cb6-10" aria-hidden="true" tabindex="-1"></a>plot_idx <span class="op">=</span> <span class="dv">0</span></span>
<span id="cb6-11"><a href="#cb6-11" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb6-12"><a href="#cb6-12" aria-hidden="true" tabindex="-1"></a><span class="cf">for</span> result <span class="kw">in</span> test_results_s3_base:</span>
<span id="cb6-13"><a href="#cb6-13" aria-hidden="true" tabindex="-1"></a>    <span class="co"># Stop if we've filled all 9 subplots</span></span>
<span id="cb6-14"><a href="#cb6-14" aria-hidden="true" tabindex="-1"></a>    <span class="cf">if</span> plot_idx <span class="op">&gt;=</span> <span class="dv">9</span>:</span>
<span id="cb6-15"><a href="#cb6-15" aria-hidden="true" tabindex="-1"></a>        <span class="cf">break</span></span>
<span id="cb6-16"><a href="#cb6-16" aria-hidden="true" tabindex="-1"></a>        </span>
<span id="cb6-17"><a href="#cb6-17" aria-hidden="true" tabindex="-1"></a>    <span class="co"># Check if this is the specific model we want</span></span>
<span id="cb6-18"><a href="#cb6-18" aria-hidden="true" tabindex="-1"></a>    <span class="cf">if</span> result.get(<span class="st">'model_name'</span>) <span class="kw">and</span> <span class="st">'confusion_matrix'</span> <span class="kw">in</span> result:</span>
<span id="cb6-19"><a href="#cb6-19" aria-hidden="true" tabindex="-1"></a>        disp <span class="op">=</span> ConfusionMatrixDisplay(confusion_matrix<span class="op">=</span>result[<span class="st">'confusion_matrix'</span>])</span>
<span id="cb6-20"><a href="#cb6-20" aria-hidden="true" tabindex="-1"></a>        disp.plot(ax<span class="op">=</span>axes[plot_idx])</span>
<span id="cb6-21"><a href="#cb6-21" aria-hidden="true" tabindex="-1"></a>        axes[plot_idx].set_title(<span class="ss">f"</span><span class="sc">{</span>result[<span class="st">'model_name'</span>]<span class="sc">}</span><span class="ss">"</span>)</span>
<span id="cb6-22"><a href="#cb6-22" aria-hidden="true" tabindex="-1"></a>        </span>
<span id="cb6-23"><a href="#cb6-23" aria-hidden="true" tabindex="-1"></a>        <span class="co"># Add red border if this is Model_5_2L_32U</span></span>
<span id="cb6-24"><a href="#cb6-24" aria-hidden="true" tabindex="-1"></a>        <span class="cf">if</span> result[<span class="st">'model_name'</span>] <span class="op">==</span> <span class="st">'Model_5_2L_32U'</span>:</span>
<span id="cb6-25"><a href="#cb6-25" aria-hidden="true" tabindex="-1"></a>            <span class="cf">for</span> spine <span class="kw">in</span> axes[plot_idx].spines.values():</span>
<span id="cb6-26"><a href="#cb6-26" aria-hidden="true" tabindex="-1"></a>                spine.set_edgecolor(<span class="st">'red'</span>)</span>
<span id="cb6-27"><a href="#cb6-27" aria-hidden="true" tabindex="-1"></a>                spine.set_linewidth(<span class="dv">3</span>)</span>
<span id="cb6-28"><a href="#cb6-28" aria-hidden="true" tabindex="-1"></a>        </span>
<span id="cb6-29"><a href="#cb6-29" aria-hidden="true" tabindex="-1"></a>        plot_idx <span class="op">+=</span> <span class="dv">1</span></span>
<span id="cb6-30"><a href="#cb6-30" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb6-31"><a href="#cb6-31" aria-hidden="true" tabindex="-1"></a><span class="co"># Hide any remaining empty subplots</span></span>
<span id="cb6-32"><a href="#cb6-32" aria-hidden="true" tabindex="-1"></a><span class="cf">for</span> i <span class="kw">in</span> <span class="bu">range</span>(plot_idx, <span class="dv">9</span>):</span>
<span id="cb6-33"><a href="#cb6-33" aria-hidden="true" tabindex="-1"></a>    axes[i].axis(<span class="st">'off'</span>)</span>
<span id="cb6-34"><a href="#cb6-34" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb6-35"><a href="#cb6-35" aria-hidden="true" tabindex="-1"></a>plt.show()</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
<figure id="fig-2" class="figure">
  <div style="text-align: center; margin-bottom: 1rem;">
    <div style="font-size: 20pt; font-weight: normal; color: #2c3e50;">Comparison of Confusion Matrices for Baseline Models</div>
  </div>
  <img src="../assets/student_dropout/figures/cm_all_models_nn_red_square.png" style="width: 70%; max-width: 600px; margin: 0 auto; display: block;" alt="Confusion matrices for all configurations" class="figure-img">
  <figcaption>Figure 2: Confusion matrices across all baseline neural network configurations</figcaption>
</figure>
<p>Figure 2 presents confusion matrices for all nine baseline Stage 3 model architectures evaluated in the systematic architecture search (Figure 1, Table 2), displayed in a 3×3 grid enabling comprehensive comparative assessment of classification performance. Each confusion matrix quantifies the four classification outcomes on the held-out test set: true negatives (TN, students correctly predicted NOT to complete), false positives (FP, completers incorrectly predicted to drop out), false negatives (FN, dropouts incorrectly predicted to complete), and true positives (TP, students correctly predicted to drop out). The red border highlights Model_5_2L_32U (2 layers, 32 units), the best-performing architecture based on validation ROC-AUC (0.9846).</p>
<p>Across all nine configurations, the matrices reveal remarkably consistent classification patterns reflecting both model quality and class imbalance characteristics. Given the binary classification where CompletedCourse=1 (positive class) represents course completion and 0 represents dropout, the confusion matrices show: true positives (TP, completers correctly identified, typically 3,200-3,270 of 3,976 test samples), false negatives (FN, completers misclassified as dropouts, 119-182), false positives (FP, dropouts misclassified as completers, 17-77), and true negatives (TN, dropouts correctly identified, 509-569). The dominant TP counts reflect the ~85% completion rate in the test set, demonstrating high sensitivity in identifying the majority class.</p>
<p>Performance variability manifests primarily in the minority class (dropout) predictions: TN counts range from 509 to 569 across configurations, representing successful dropout identification rates of 75-85% of dropout cases. The best-performing models (e.g., Model_5_2L_32U with TN=519, FP=67, FN=119, TP=3,271) achieve balanced performance, correctly identifying approximately 88% of dropouts (TN/(TN+FP) = 519/586 ≈ 0.89) while maintaining high completion identification (TP/(TP+FN) = 3,271/3,390 ≈ 0.96). FP counts remain relatively low (17-77), though these represent the most operationally concerning errors, dropouts predicted to complete who receive no intervention. The inverse relationship between TN and FP across models reflects varying decision boundary conservativeness, with some architectures prioritizing dropout detection sensitivity (higher TN, higher FP) versus specificity (lower FP, lower TN).</p>
<p>The visual comparison reveals that even architecturally diverse models, from shallow 1-layer networks to deeper 3-layer configurations, achieve similar confusion matrix structures, corroborating the narrow performance variance documented in Table 2. This homogeneity validates that Stage 3’s rich academic performance features (particularly the engineered RateModuleSuccess metric) enable robust classification regardless of model complexity. The minimal architectural sensitivity suggests practitioners can select simpler, computationally efficient models (e.g., Model_5_2L_32U with 2 layers) without sacrificing predictive accuracy, prioritizing deployment efficiency over architectural optimization when working with high-quality feature sets.</p>
</section>
<section id="hyperparameter-tuning-and-regularization-analysis" class="level3">
<h3 class="anchored" data-anchor-id="hyperparameter-tuning-and-regularization-analysis">Hyperparameter Tuning and Regularization Analysis</h3>
<p>Following baseline model evaluation, systematic hyperparameter optimization explored whether L1/L2 regularization could further improve model performance or reduce potential overfitting suggested by the tight training-validation loss convergence observed in Figure 1. The hyperparameter search employed a focused grid spanning batch sizes (16, 32) and regularization strengths (L1: [0.01, 0.001], L2: [0.01, 0.001]), while maintaining consistent learning rate (0.001), optimizer (Adam), and dropout rate (0.2) based on baseline results. This generated 8 model configurations evaluated through the same deterministic training protocol, with early stopping (patience=3) monitoring validation loss.</p>
<p>The systematic search revealed that hyperparameter tuning yielded minimal performance improvements over baseline configurations. As documented in Table 1, the best tuned Stage 3 model achieved ROC-AUC=0.9838, marginally lower than the baseline Model_5_2L_32U (ROC-AUC=0.9846). The optimal tuned configuration incorporated L1/L2 regularization (0.001 each) with batch size 32, suggesting that modest regularization prevents overfitting on the expanded Stage 3 feature space without compromising predictive accuracy. However, the narrow performance variance across all tuned configurations (ROC-AUC range: ~0.980-0.984) indicates that Stage 3’s rich academic performance features enable robust prediction regardless of regularization strength, echoing the architectural insensitivity observed in baseline models.</p>
<div id="250a503b" class="cell" data-execution_count="9">
<div class="sourceCode cell-code" id="cb7"><pre class="sourceCode python code-overflow-wrap code-with-copy"><code class="sourceCode python"><span id="cb7-1"><a href="#cb7-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Suppress TensorFlow warnings and logs</span></span>
<span id="cb7-2"><a href="#cb7-2" aria-hidden="true" tabindex="-1"></a>os.environ[<span class="st">'TF_CPP_MIN_LOG_LEVEL'</span>] <span class="op">=</span> <span class="st">'3'</span>  <span class="co"># Suppress all TF logs (0=all, 1=info, 2=warning, 3=error)</span></span>
<span id="cb7-3"><a href="#cb7-3" aria-hidden="true" tabindex="-1"></a>os.environ[<span class="st">'TF_ENABLE_ONEDNN_OPTS'</span>] <span class="op">=</span> <span class="st">'0'</span>  <span class="co"># Disable oneDNN optimizations warnings</span></span>
<span id="cb7-4"><a href="#cb7-4" aria-hidden="true" tabindex="-1"></a>warnings.filterwarnings(<span class="st">'ignore'</span>)</span>
<span id="cb7-5"><a href="#cb7-5" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb7-6"><a href="#cb7-6" aria-hidden="true" tabindex="-1"></a><span class="co"># Additional TensorFlow logging suppression</span></span>
<span id="cb7-7"><a href="#cb7-7" aria-hidden="true" tabindex="-1"></a>tf.get_logger().setLevel(<span class="st">'ERROR'</span>)</span>
<span id="cb7-8"><a href="#cb7-8" aria-hidden="true" tabindex="-1"></a>tf.autograph.set_verbosity(<span class="dv">0</span>)</span>
<span id="cb7-9"><a href="#cb7-9" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb7-10"><a href="#cb7-10" aria-hidden="true" tabindex="-1"></a><span class="kw">def</span> set_global_determinism(seed):</span>
<span id="cb7-11"><a href="#cb7-11" aria-hidden="true" tabindex="-1"></a>    <span class="co">"""Set seeds for reproducible results"""</span></span>
<span id="cb7-12"><a href="#cb7-12" aria-hidden="true" tabindex="-1"></a>    tf.random.set_seed(seed)</span>
<span id="cb7-13"><a href="#cb7-13" aria-hidden="true" tabindex="-1"></a>    np.random.seed(seed)</span>
<span id="cb7-14"><a href="#cb7-14" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb7-15"><a href="#cb7-15" aria-hidden="true" tabindex="-1"></a><span class="kw">def</span> create_model_tuning(input_dim, output_dim, layers<span class="op">=</span><span class="dv">2</span>, units<span class="op">=</span><span class="dv">32</span>, dropout<span class="op">=</span><span class="fl">0.2</span>, batch_size<span class="op">=</span><span class="dv">16</span>,</span>
<span id="cb7-16"><a href="#cb7-16" aria-hidden="true" tabindex="-1"></a>                       lr<span class="op">=</span><span class="fl">0.001</span>, optimizer<span class="op">=</span><span class="st">'adam'</span>, seed<span class="op">=</span><span class="dv">42</span>,</span>
<span id="cb7-17"><a href="#cb7-17" aria-hidden="true" tabindex="-1"></a>                       l1_reg<span class="op">=</span><span class="fl">0.0</span>, l2_reg<span class="op">=</span><span class="fl">0.0</span>):</span>
<span id="cb7-18"><a href="#cb7-18" aria-hidden="true" tabindex="-1"></a>    <span class="co">"""Create a deterministic neural network model with L1/L2 regularization"""</span></span>
<span id="cb7-19"><a href="#cb7-19" aria-hidden="true" tabindex="-1"></a>    <span class="co"># Reset seeds before each model creation</span></span>
<span id="cb7-20"><a href="#cb7-20" aria-hidden="true" tabindex="-1"></a>    tf.random.set_seed(seed)</span>
<span id="cb7-21"><a href="#cb7-21" aria-hidden="true" tabindex="-1"></a>    np.random.seed(seed)</span>
<span id="cb7-22"><a href="#cb7-22" aria-hidden="true" tabindex="-1"></a>    </span>
<span id="cb7-23"><a href="#cb7-23" aria-hidden="true" tabindex="-1"></a>    <span class="co"># Create regularization object</span></span>
<span id="cb7-24"><a href="#cb7-24" aria-hidden="true" tabindex="-1"></a>    kernel_regularizer <span class="op">=</span> regularizers.L1L2(l1<span class="op">=</span>l1_reg, l2<span class="op">=</span>l2_reg) <span class="cf">if</span> (l1_reg <span class="op">&gt;</span> <span class="dv">0</span> <span class="kw">or</span> l2_reg <span class="op">&gt;</span> <span class="dv">0</span>) <span class="cf">else</span> <span class="va">None</span></span>
<span id="cb7-25"><a href="#cb7-25" aria-hidden="true" tabindex="-1"></a>    </span>
<span id="cb7-26"><a href="#cb7-26" aria-hidden="true" tabindex="-1"></a>    model <span class="op">=</span> Sequential(name<span class="op">=</span><span class="ss">f"model_</span><span class="sc">{</span>layers<span class="sc">}</span><span class="ss">L_</span><span class="sc">{</span>units<span class="sc">}</span><span class="ss">U"</span>)</span>
<span id="cb7-27"><a href="#cb7-27" aria-hidden="true" tabindex="-1"></a>    model.add(InputLayer(shape<span class="op">=</span>(input_dim,)))</span>
<span id="cb7-28"><a href="#cb7-28" aria-hidden="true" tabindex="-1"></a>    </span>
<span id="cb7-29"><a href="#cb7-29" aria-hidden="true" tabindex="-1"></a>    <span class="cf">for</span> _ <span class="kw">in</span> <span class="bu">range</span>(layers):</span>
<span id="cb7-30"><a href="#cb7-30" aria-hidden="true" tabindex="-1"></a>        model.add(Dense(units, activation<span class="op">=</span><span class="st">'relu'</span>, </span>
<span id="cb7-31"><a href="#cb7-31" aria-hidden="true" tabindex="-1"></a>                       kernel_regularizer<span class="op">=</span>kernel_regularizer,</span>
<span id="cb7-32"><a href="#cb7-32" aria-hidden="true" tabindex="-1"></a>                       kernel_initializer<span class="op">=</span>tf.keras.initializers.GlorotUniform(seed<span class="op">=</span>seed),</span>
<span id="cb7-33"><a href="#cb7-33" aria-hidden="true" tabindex="-1"></a>                       bias_initializer<span class="op">=</span>tf.keras.initializers.Zeros()))</span>
<span id="cb7-34"><a href="#cb7-34" aria-hidden="true" tabindex="-1"></a>        model.add(Dropout(dropout, seed<span class="op">=</span>seed))</span>
<span id="cb7-35"><a href="#cb7-35" aria-hidden="true" tabindex="-1"></a>    </span>
<span id="cb7-36"><a href="#cb7-36" aria-hidden="true" tabindex="-1"></a>    model.add(Dense(output_dim, activation<span class="op">=</span><span class="st">'softmax'</span>,</span>
<span id="cb7-37"><a href="#cb7-37" aria-hidden="true" tabindex="-1"></a>                   kernel_regularizer<span class="op">=</span>kernel_regularizer,</span>
<span id="cb7-38"><a href="#cb7-38" aria-hidden="true" tabindex="-1"></a>                   kernel_initializer<span class="op">=</span>tf.keras.initializers.GlorotUniform(seed<span class="op">=</span>seed),</span>
<span id="cb7-39"><a href="#cb7-39" aria-hidden="true" tabindex="-1"></a>                   bias_initializer<span class="op">=</span>tf.keras.initializers.Zeros()))</span>
<span id="cb7-40"><a href="#cb7-40" aria-hidden="true" tabindex="-1"></a>    </span>
<span id="cb7-41"><a href="#cb7-41" aria-hidden="true" tabindex="-1"></a>    <span class="co"># Choose optimizer</span></span>
<span id="cb7-42"><a href="#cb7-42" aria-hidden="true" tabindex="-1"></a>    <span class="cf">if</span> optimizer.lower() <span class="op">==</span> <span class="st">'adam'</span>:</span>
<span id="cb7-43"><a href="#cb7-43" aria-hidden="true" tabindex="-1"></a>        opt <span class="op">=</span> Adam(learning_rate<span class="op">=</span>lr)</span>
<span id="cb7-44"><a href="#cb7-44" aria-hidden="true" tabindex="-1"></a>    <span class="cf">elif</span> optimizer.lower() <span class="op">==</span> <span class="st">'rmsprop'</span>:</span>
<span id="cb7-45"><a href="#cb7-45" aria-hidden="true" tabindex="-1"></a>        opt <span class="op">=</span> RMSprop(learning_rate<span class="op">=</span>lr)</span>
<span id="cb7-46"><a href="#cb7-46" aria-hidden="true" tabindex="-1"></a>    <span class="cf">else</span>:</span>
<span id="cb7-47"><a href="#cb7-47" aria-hidden="true" tabindex="-1"></a>        opt <span class="op">=</span> Adam(learning_rate<span class="op">=</span>lr)  <span class="co"># default</span></span>
<span id="cb7-48"><a href="#cb7-48" aria-hidden="true" tabindex="-1"></a>    </span>
<span id="cb7-49"><a href="#cb7-49" aria-hidden="true" tabindex="-1"></a>    model.<span class="bu">compile</span>(optimizer<span class="op">=</span>opt,</span>
<span id="cb7-50"><a href="#cb7-50" aria-hidden="true" tabindex="-1"></a>                 loss<span class="op">=</span><span class="st">'sparse_categorical_crossentropy'</span>,</span>
<span id="cb7-51"><a href="#cb7-51" aria-hidden="true" tabindex="-1"></a>                 metrics<span class="op">=</span>[<span class="st">'accuracy'</span>])</span>
<span id="cb7-52"><a href="#cb7-52" aria-hidden="true" tabindex="-1"></a>    <span class="cf">return</span> model</span>
<span id="cb7-53"><a href="#cb7-53" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb7-54"><a href="#cb7-54" aria-hidden="true" tabindex="-1"></a><span class="co"># Get dimensions (assuming X_train, y_train are defined)</span></span>
<span id="cb7-55"><a href="#cb7-55" aria-hidden="true" tabindex="-1"></a>input_dim <span class="op">=</span> X_train_scaled_s3.shape[<span class="dv">1</span>]</span>
<span id="cb7-56"><a href="#cb7-56" aria-hidden="true" tabindex="-1"></a>output_dim <span class="op">=</span> <span class="bu">len</span>(np.unique(y_train_s3))</span>
<span id="cb7-57"><a href="#cb7-57" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb7-58"><a href="#cb7-58" aria-hidden="true" tabindex="-1"></a><span class="co"># Hyperparameter grid with L1/L2 regularization options</span></span>
<span id="cb7-59"><a href="#cb7-59" aria-hidden="true" tabindex="-1"></a>hyperparameter_config <span class="op">=</span> {</span>
<span id="cb7-60"><a href="#cb7-60" aria-hidden="true" tabindex="-1"></a>    <span class="st">'dropout'</span>: [<span class="fl">0.2</span>], </span>
<span id="cb7-61"><a href="#cb7-61" aria-hidden="true" tabindex="-1"></a>    <span class="st">'lr'</span>: [<span class="fl">0.001</span>],</span>
<span id="cb7-62"><a href="#cb7-62" aria-hidden="true" tabindex="-1"></a>    <span class="st">'optimizer'</span>: [<span class="st">'adam'</span>],</span>
<span id="cb7-63"><a href="#cb7-63" aria-hidden="true" tabindex="-1"></a>    <span class="st">'batch_size'</span>: [<span class="dv">16</span>, <span class="dv">32</span>],</span>
<span id="cb7-64"><a href="#cb7-64" aria-hidden="true" tabindex="-1"></a>    <span class="st">'l1_reg'</span>: [<span class="fl">0.01</span>, <span class="fl">0.001</span>],  <span class="co"># L1 regularization strengths</span></span>
<span id="cb7-65"><a href="#cb7-65" aria-hidden="true" tabindex="-1"></a>    <span class="st">'l2_reg'</span>: [<span class="fl">0.01</span>, <span class="fl">0.001</span>]   <span class="co"># L2 regularization strengths</span></span>
<span id="cb7-66"><a href="#cb7-66" aria-hidden="true" tabindex="-1"></a>}</span>
<span id="cb7-67"><a href="#cb7-67" aria-hidden="true" tabindex="-1"></a>models_tuning_s3 <span class="op">=</span> []</span>
<span id="cb7-68"><a href="#cb7-68" aria-hidden="true" tabindex="-1"></a>histories_tuning_s3 <span class="op">=</span> []</span>
<span id="cb7-69"><a href="#cb7-69" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb7-70"><a href="#cb7-70" aria-hidden="true" tabindex="-1"></a><span class="co"># Generate all combinations of hyperparameters</span></span>
<span id="cb7-71"><a href="#cb7-71" aria-hidden="true" tabindex="-1"></a>keys, values <span class="op">=</span> <span class="bu">zip</span>(<span class="op">*</span>hyperparameter_config.items())</span>
<span id="cb7-72"><a href="#cb7-72" aria-hidden="true" tabindex="-1"></a>configs <span class="op">=</span> [<span class="bu">dict</span>(<span class="bu">zip</span>(keys, v)) <span class="cf">for</span> v <span class="kw">in</span> product(<span class="op">*</span>values)]</span>
<span id="cb7-73"><a href="#cb7-73" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb7-74"><a href="#cb7-74" aria-hidden="true" tabindex="-1"></a><span class="co"># Initialize progress bar</span></span>
<span id="cb7-75"><a href="#cb7-75" aria-hidden="true" tabindex="-1"></a>progress_bar <span class="op">=</span> tqdm(configs, desc<span class="op">=</span><span class="st">"Hyperparameter Tuning"</span>, unit<span class="op">=</span><span class="st">"model"</span>)</span>
<span id="cb7-76"><a href="#cb7-76" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb7-77"><a href="#cb7-77" aria-hidden="true" tabindex="-1"></a><span class="cf">for</span> i, config <span class="kw">in</span> <span class="bu">enumerate</span>(progress_bar):</span>
<span id="cb7-78"><a href="#cb7-78" aria-hidden="true" tabindex="-1"></a>    <span class="co"># Update progress bar description with current config</span></span>
<span id="cb7-79"><a href="#cb7-79" aria-hidden="true" tabindex="-1"></a>    short_desc <span class="op">=</span> (<span class="ss">f"do:</span><span class="sc">{</span>config[<span class="st">'dropout'</span>]<span class="sc">}</span><span class="ss"> lr:</span><span class="sc">{</span>config[<span class="st">'lr'</span>]<span class="sc">}</span><span class="ss"> opt:</span><span class="sc">{</span>config[<span class="st">'optimizer'</span>]<span class="sc">}</span><span class="ss"> "</span></span>
<span id="cb7-80"><a href="#cb7-80" aria-hidden="true" tabindex="-1"></a>                 <span class="ss">f"bs:</span><span class="sc">{</span>config[<span class="st">'batch_size'</span>]<span class="sc">}</span><span class="ss"> L1:</span><span class="sc">{</span>config[<span class="st">'l1_reg'</span>]<span class="sc">}</span><span class="ss"> L2:</span><span class="sc">{</span>config[<span class="st">'l2_reg'</span>]<span class="sc">}</span><span class="ss">"</span>)</span>
<span id="cb7-81"><a href="#cb7-81" aria-hidden="true" tabindex="-1"></a>    progress_bar.set_postfix(config<span class="op">=</span>short_desc)</span>
<span id="cb7-82"><a href="#cb7-82" aria-hidden="true" tabindex="-1"></a>    </span>
<span id="cb7-83"><a href="#cb7-83" aria-hidden="true" tabindex="-1"></a>    <span class="co"># Set unique but deterministic seed for each model</span></span>
<span id="cb7-84"><a href="#cb7-84" aria-hidden="true" tabindex="-1"></a>    model_seed <span class="op">=</span> <span class="dv">42</span> <span class="op">+</span> i</span>
<span id="cb7-85"><a href="#cb7-85" aria-hidden="true" tabindex="-1"></a>    set_global_determinism(model_seed)</span>
<span id="cb7-86"><a href="#cb7-86" aria-hidden="true" tabindex="-1"></a>    </span>
<span id="cb7-87"><a href="#cb7-87" aria-hidden="true" tabindex="-1"></a>    <span class="co"># Clear session and memory</span></span>
<span id="cb7-88"><a href="#cb7-88" aria-hidden="true" tabindex="-1"></a>    tf.keras.backend.clear_session()</span>
<span id="cb7-89"><a href="#cb7-89" aria-hidden="true" tabindex="-1"></a>    gc.collect()</span>
<span id="cb7-90"><a href="#cb7-90" aria-hidden="true" tabindex="-1"></a>    </span>
<span id="cb7-91"><a href="#cb7-91" aria-hidden="true" tabindex="-1"></a>    <span class="co"># Early stopping</span></span>
<span id="cb7-92"><a href="#cb7-92" aria-hidden="true" tabindex="-1"></a>    early_stop <span class="op">=</span> EarlyStopping(monitor<span class="op">=</span><span class="st">'val_loss'</span>, patience<span class="op">=</span><span class="dv">3</span>, </span>
<span id="cb7-93"><a href="#cb7-93" aria-hidden="true" tabindex="-1"></a>                              restore_best_weights<span class="op">=</span><span class="va">True</span>, verbose<span class="op">=</span><span class="dv">0</span>)</span>
<span id="cb7-94"><a href="#cb7-94" aria-hidden="true" tabindex="-1"></a>    </span>
<span id="cb7-95"><a href="#cb7-95" aria-hidden="true" tabindex="-1"></a>    <span class="co"># Create model with current config (excluding batch_size which is for training)</span></span>
<span id="cb7-96"><a href="#cb7-96" aria-hidden="true" tabindex="-1"></a>    model_config <span class="op">=</span> {k: v <span class="cf">for</span> k, v <span class="kw">in</span> config.items() <span class="cf">if</span> k <span class="op">!=</span> <span class="st">'batch_size'</span>}</span>
<span id="cb7-97"><a href="#cb7-97" aria-hidden="true" tabindex="-1"></a>    model_tuning_s3 <span class="op">=</span> create_model_tuning(input_dim, output_dim, seed<span class="op">=</span>model_seed, <span class="op">**</span>model_config)</span>
<span id="cb7-98"><a href="#cb7-98" aria-hidden="true" tabindex="-1"></a>    </span>
<span id="cb7-99"><a href="#cb7-99" aria-hidden="true" tabindex="-1"></a>    <span class="co"># Train model (NON-VERBOSE)</span></span>
<span id="cb7-100"><a href="#cb7-100" aria-hidden="true" tabindex="-1"></a>    history_tuning_s3 <span class="op">=</span> model_tuning_s3.fit(</span>
<span id="cb7-101"><a href="#cb7-101" aria-hidden="true" tabindex="-1"></a>        X_train_scaled_s3, y_train_s3,</span>
<span id="cb7-102"><a href="#cb7-102" aria-hidden="true" tabindex="-1"></a>        validation_data<span class="op">=</span>(X_val_scaled_s3, y_val_s3),</span>
<span id="cb7-103"><a href="#cb7-103" aria-hidden="true" tabindex="-1"></a>        batch_size<span class="op">=</span>config[<span class="st">'batch_size'</span>],</span>
<span id="cb7-104"><a href="#cb7-104" aria-hidden="true" tabindex="-1"></a>        epochs<span class="op">=</span><span class="dv">5</span>,</span>
<span id="cb7-105"><a href="#cb7-105" aria-hidden="true" tabindex="-1"></a>        callbacks<span class="op">=</span>[early_stop],</span>
<span id="cb7-106"><a href="#cb7-106" aria-hidden="true" tabindex="-1"></a>        shuffle<span class="op">=</span><span class="va">True</span>,  <span class="co"># Deterministic due to seed</span></span>
<span id="cb7-107"><a href="#cb7-107" aria-hidden="true" tabindex="-1"></a>        verbose<span class="op">=</span><span class="dv">0</span>  <span class="co"># Silent training</span></span>
<span id="cb7-108"><a href="#cb7-108" aria-hidden="true" tabindex="-1"></a>    )</span>
<span id="cb7-109"><a href="#cb7-109" aria-hidden="true" tabindex="-1"></a>    </span>
<span id="cb7-110"><a href="#cb7-110" aria-hidden="true" tabindex="-1"></a>    <span class="co"># Evaluate model (NON-VERBOSE)</span></span>
<span id="cb7-111"><a href="#cb7-111" aria-hidden="true" tabindex="-1"></a>    val_loss_tuning_s3, val_acc_tuning_s3 <span class="op">=</span> model_tuning_s3.evaluate(X_val_scaled_s3, y_val_s3, verbose<span class="op">=</span><span class="dv">0</span>)</span>
<span id="cb7-112"><a href="#cb7-112" aria-hidden="true" tabindex="-1"></a>    </span>
<span id="cb7-113"><a href="#cb7-113" aria-hidden="true" tabindex="-1"></a>    </span>
<span id="cb7-114"><a href="#cb7-114" aria-hidden="true" tabindex="-1"></a>    <span class="co"># Store results</span></span>
<span id="cb7-115"><a href="#cb7-115" aria-hidden="true" tabindex="-1"></a>    models_tuning_s3.append(model_tuning_s3)</span>
<span id="cb7-116"><a href="#cb7-116" aria-hidden="true" tabindex="-1"></a>    histories_tuning_s3.append({</span>
<span id="cb7-117"><a href="#cb7-117" aria-hidden="true" tabindex="-1"></a>        <span class="st">"config"</span>: config,</span>
<span id="cb7-118"><a href="#cb7-118" aria-hidden="true" tabindex="-1"></a>        <span class="st">"model"</span>: model_tuning_s3,</span>
<span id="cb7-119"><a href="#cb7-119" aria-hidden="true" tabindex="-1"></a>        <span class="st">"val_loss"</span>: val_loss_tuning_s3,</span>
<span id="cb7-120"><a href="#cb7-120" aria-hidden="true" tabindex="-1"></a>        <span class="st">"val_accuracy"</span>: val_acc_tuning_s3,</span>
<span id="cb7-121"><a href="#cb7-121" aria-hidden="true" tabindex="-1"></a>        <span class="st">"history"</span>: history_tuning_s3,</span>
<span id="cb7-122"><a href="#cb7-122" aria-hidden="true" tabindex="-1"></a>        <span class="st">"seed"</span>: model_seed</span>
<span id="cb7-123"><a href="#cb7-123" aria-hidden="true" tabindex="-1"></a>    })</span>
<span id="cb7-124"><a href="#cb7-124" aria-hidden="true" tabindex="-1"></a>    </span>
<span id="cb7-125"><a href="#cb7-125" aria-hidden="true" tabindex="-1"></a>    <span class="co"># Clean up</span></span>
<span id="cb7-126"><a href="#cb7-126" aria-hidden="true" tabindex="-1"></a>    gc.collect()</span>
<span id="cb7-127"><a href="#cb7-127" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb7-128"><a href="#cb7-128" aria-hidden="true" tabindex="-1"></a><span class="co"># Close progress bar</span></span>
<span id="cb7-129"><a href="#cb7-129" aria-hidden="true" tabindex="-1"></a>progress_bar.close()</span>
<span id="cb7-130"><a href="#cb7-130" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb7-131"><a href="#cb7-131" aria-hidden="true" tabindex="-1"></a><span class="bu">print</span>(<span class="ss">f"Hyperparameter tuning completed. Trained </span><span class="sc">{</span><span class="bu">len</span>(models_tuning_s3)<span class="sc">}</span><span class="ss"> models."</span>)</span>
<span id="cb7-132"><a href="#cb7-132" aria-hidden="true" tabindex="-1"></a><span class="bu">print</span>(<span class="st">'Models: models_tuning_s3, Histories: histories_tuning_s3'</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
<figure id="fig-3" class="figure">
  <div style="text-align: center; margin-bottom: 1rem;">
    <div style="font-size: 20pt; font-weight: normal; color: #2c3e50;">Hyperparameter-Tuned Models Performance</div>
  </div>
  <img src="../assets/student_dropout/figures/tuned_nn_models_best_highlighted.png" style="width: 70%; max-width: 600px; margin: 0 auto; display: block;" alt="Tuned models comparison" class="figure-img">
  <figcaption>Figure 3: Test set performance comparison across 8 hyperparameter-tuned configurations with best model highlighted</figcaption>
</figure>
<p>Figure 3 displays test set confusion matrices for the 8 systematically tuned neural network configurations, arranged in a 4×2 grid. Each confusion matrix shows classification outcomes on the held-out test set, with the best-performing model (L1=0.001, L2=0.001, batch_size=32) highlighted with a red border in the bottom-right position. The grid reveals remarkably consistent classification patterns across different combinations of batch size and L1/L2 regularization strengths, with all configurations yielding nearly equivalent performance (ROC-AUC range: approximately 0.980-0.984, span ~0.004). True negative counts (TN, dropouts correctly identified) cluster tightly between 510-569 across models, while true positive counts (TP, completers correctly identified) range from 3,208-3,249, demonstrating minimal variability. The false positive rates (FP, dropouts misclassified as completers) remain consistently low (17-76), and false negative rates (FN, completers misclassified as dropouts) show modest variation (142-182). This homogeneity corroborates the finding that data quality dominates hyperparameter optimization for this task: when working with strong predictive features (particularly the engineered RateModuleSuccess metric), the choice of regularization strength becomes a minor consideration.</p>
<p>The highlighted optimal configuration (ROC-AUC=0.9838) achieves marginally lower performance than the baseline Model_5_2L_32U (ROC-AUC=0.9846)(See figure 4), indicating that L1/L2 regularization did not improve discrimination capability despite the perceived overfitting risk suggested by high baseline performance. This counterintuitive result validates that the baseline models’ high ROC-AUC scores reflect genuine predictive signal from academic performance features rather than overfitting artifacts. The visualization guides practitioners in understanding that for Stage 3’s rich feature set, conservative hyperparameter choices (modest regularization, standard batch sizes) achieve near-ceiling performance, reducing the need for extensive computational search during model development.</p>
</section>
<section id="best-baseline-vs-best-tuned-model" class="level3">
<h3 class="anchored" data-anchor-id="best-baseline-vs-best-tuned-model">Best Baseline vs Best Tuned Model</h3>
<p>Figure 4 presents a side-by-side confusion matrix comparison between the best baseline architecture (Model_5_2L_32U: 2 layers, 32 units, dropout=0.2) and the best hyperparameter-tuned model evaluated on the Stage 3 test set (n=3,976). This direct comparison quantifies the marginal performance gains from systematic hyperparameter optimization, enabling assessment of whether tuning justifies additional computational investment. Both confusion matrices display the four classification outcomes: TP (completers correctly identified), FN (completers misclassified as dropouts), FP (dropouts misclassified as completers), and TN (dropouts correctly identified).</p>
<figure id="fig-4" class="figure">
  <div style="text-align: center; margin-bottom: 1rem;">
    <div style="font-size: 20pt; font-weight: normal; color: #2c3e50;">Comparison of Best Baseline vs Best Tuned Model</div>
  </div>
  <img src="../assets/student_dropout/figures/comparison_cm_best_nn_s3.png" style="width: 70%; max-width: 600px; margin: 0 auto; display: block;" alt="Best model confusion matrix" class="figure-img">
  <figcaption>Figure 4: Side-by-side confusion matrix comparison of best baseline (Model_5_2L_32U) versus best tuned model on Stage 3 test set</figcaption>
</figure>
<p>The baseline model (left panel) achieves TN=519, FP=67, FN=119, TP=3,271, yielding dropout detection accuracy of 88.6% (TN/(TN+FP)) and completion detection accuracy of 96.5% (TP/(TP+FN)). The tuned model (right panel, TN=540, FP=46, FN=141, TP=3,249) demonstrates the effect of L1/L2 regularization (0.001 each) on decision boundary placement, achieving slightly higher precision for dropout detection (92.2% vs 88.6%) at the cost of modestly reduced completion recall. Though performance differences remain minimal given the narrow ROC-AUC variance (0.9846 vs 0.9838) documented in Table 1, the comparison reveals that hyperparameter optimization primarily shifts the precision-recall trade-off toward more conservative dropout predictions.</p>
<p>This marginal difference validates the finding that for Stage 3’s rich feature set, baseline configurations achieve near-optimal performance without extensive tuning. The visual comparison enables us to assess whether tuning’s computational cost, systematic grid search across learning rates, batch sizes, dropout rates, and regularization strengths, justifies &lt;1% ROC-AUC improvements. For deployment contexts prioritizing rapid model development or computational efficiency, the baseline model provides operationally equivalent performance. However, for resource-rich institutions seeking maximal precision to minimize unnecessary interventions, the tuned model’s slightly higher specificity (lower FP rate) may warrant the additional optimization effort. The tuned model shown here represents the best configuration identified during hyperparameter search and serves as the template for final production deployment (Figure 6).</p>
</section>
<section id="training-dynamics-and-performance-of-the-optimal-model" class="level3">
<h3 class="anchored" data-anchor-id="training-dynamics-and-performance-of-the-optimal-model">Training Dynamics and Performance of the Optimal Model</h3>
<p>Figure 5 displays the complete training trajectory for the optimal model identified through hyperparameter search, the configuration with L1/L2 regularization (0.001 each) and batch size 32 that achieved the best tuned performance. After identifying this optimal configuration from the 8-model grid search (which used 5 epochs), the model was retrained with an extended training budget of 10 epochs to capture its full learning potential. The left panel shows loss convergence across these 10 training epochs, with both training (solid line) and validation (dashed line) loss decreasing monotonically before plateauing around epoch 6-8, indicating stable optimization without oscillation.</p>
<figure id="fig-5" class="figure">
  <div style="text-align: center; margin-bottom: 1rem;">
    <div style="font-size: 20pt; font-weight: normal; color: #2c3e50;">Optimal Model Training Dynamics</div>
  </div>
  <div style="display: flex; gap: 1.5rem; justify-content: center; flex-wrap: wrap;">
    <img src="../assets/student_dropout/figures/learning_curve_final_model.png" style="width: 40%; min-width: 300px;" alt="Final model loss convergence" class="figure-img">
    <img src="../assets/student_dropout/figures/accuracy_curve_final_nn_s3_model.png" style="width: 40%; min-width: 300px;" alt="Final model accuracy" class="figure-img">
  </div>
  <figcaption>Figure 5: Training dynamics for the optimal model configuration (L1=0.001, L2=0.001, batch_size=32)</figcaption>
</figure>
<p>The right panel displays accuracy progression, with validation accuracy rapidly ascending to &gt;95% within the first 3-4 epochs before plateauing. The tight convergence between training and validation curves throughout the 10-epoch training period validates effective regularization: the model achieved strong test set discrimination (ROC-AUC=0.9838) without memorizing training data. These dynamics confirm the model’s deployment readiness, fast convergence (reaching near-optimal performance within a few epochs), stable performance (no oscillation or divergence), and strong generalization (minimal train-validation gap) indicate robust performance on future unseen student cohorts.</p>
<figure id="fig-6" class="figure">
  <div style="text-align: center; margin-bottom: 1rem;">
    <div style="font-size: 20pt; font-weight: normal; color: #2c3e50;">Test Set Performance - Optimal Model</div>
  </div>
  <img src="../assets/student_dropout/figures/confusion_matrix_final_model.png" style="width: 70%; max-width: 350px; margin: 0 auto; display: block;" alt="Final model confusion matrix" class="figure-img">
  <figcaption>Figure 6: Confusion matrix for the optimal model evaluated on held-out test set (n=3,976)</figcaption>
</figure>
<p>Figure 6 presents the confusion matrix for the final production model, a fresh training of the optimal hyperparameter configuration (L1=0.001, L2=0.001, batch_size=32, dropout=0.2, learning rate=0.001) identified through systematic search (Figure 3, Figure 4). This model was trained independently for a fixed 10 epochs on the same training data to create a production-ready deployment artifact, providing an unbiased estimate of real-world classification performance on the held-out test set (n=3,976). The matrix quantifies the four classification outcomes: TN=536 (dropouts correctly identified), FP=50 (dropouts misclassified as completers), FN=135 (completers misclassified as dropouts), and TP=3,255 (completers correctly identified). The ~85% completion rate in the test set results in substantially higher counts in completion-related quadrants (TP and FN) compared to dropout-related quadrants (TN and FP), reflecting the natural class imbalance.</p>
<p><strong>Model Reproducibility and Stochastic Variation</strong>: The final model’s confusion matrix values differ slightly from the tuned model shown in Figure 4 (which achieved TN=540, FP=46, FN=141, TP=3,249), despite using identical hyperparameters and training data. This demonstrates an important characteristic of neural network training: models are <strong>reproducible but not identically replicable</strong>. Even with deterministic training protocols (fixed random seeds, deterministic operations), neural networks exhibit inherent stochasticity from factors including floating-point arithmetic order, GPU parallelization, and subtle differences in training iteration sequences. The small prediction differences (4-6 samples, or ~0.1% of test set) between training runs validate that the optimal hyperparameter configuration produces <strong>consistent</strong> performance (both models: ROC-AUC ~0.9838, F1 ~0.972) while demonstrating expected neural network variability. This reproducibility, without exact replication, represents best practice for production deployment: practitioners should expect minor numerical differences across retraining runs while maintaining confidence in overall performance stability.</p>
<p>The confusion matrix enables stakeholders to understand operational implications of deployment. The final model’s slightly lower precision for dropout detection (91.5% vs 92.2% in Figure 4) with marginally higher completion recall (96.0% vs 95.8%) reflects the stochastic variation in decision boundary placement, demonstrating that both models operate at functionally equivalent performance levels for institutional deployment.</p>
</section>
</section>
<section id="discussion" class="level2">
<h2 class="anchored" data-anchor-id="discussion">Discussion</h2>
<p>This systematic evaluation of neural networks for student dropout prediction yields important findings with both theoretical and practical implications for institutional deployment of early warning systems. The analysis demonstrates clear performance stratification across the three progressive data stages, quantifying the trade-off between early prediction (when interventions can have maximum impact) and prediction accuracy (which improves as more student data accumulates).</p>
<section id="data-enrichment-drives-performance-not-architectural-optimization" class="level3">
<h3 class="anchored" data-anchor-id="data-enrichment-drives-performance-not-architectural-optimization">Data Enrichment Drives Performance, Not Architectural Optimization</h3>
<p>The most striking result is the dramatic performance improvement from Stage 1 to Stage 3, with ROC-AUC increasing from approximately 0.85 (enrollment data only) to 0.887-0.888 (mid-semester engagement added) to &gt;0.98 (end-of-semester academic performance included). This 13-14 percentage point improvement in discrimination capability quantifies the value of comprehensive academic performance data, demonstrating that end-of-semester metrics, particularly the engineered RateModuleSuccess feature capturing (PassedModules - FailedModules) / AssessedModules, provide substantially stronger dropout signals than demographic and early engagement features alone <span class="citation" data-cites="goren2024early">(<a href="#ref-goren2024early" role="doc-biblioref">Goren, Cohen, and Rubinstein 2024</a>)</span>. The Stage 2 intermediate performance (~0.887 ROC-AUC) suggests that mid-semester engagement metrics (absence counts, early assessment patterns) offer modest predictive gains over enrollment features, but fail to approach the exceptional discrimination enabled by comprehensive end-of-term academic records.</p>
<p>Across all three data stages, hyperparameter optimization yielded minimal performance improvements over baseline configurations, with tuned models achieving gains typically &lt;1% in ROC-AUC. Stage 1 showed essentially identical performance between base and tuned models (0.854 vs.&nbsp;0.853), Stage 2 demonstrated marginal improvement (0.887 vs.&nbsp;0.888), and Stage 3 revealed the surprising pattern where the baseline Model_5_2L_32U (ROC-AUC=0.9846) actually outperformed the best tuned configuration (ROC-AUC=0.9838). This consistent pattern suggests that for educational tabular data with strong signal-to-noise ratios, data quality and feature engineering matter far more than architectural fine-tuning.</p>
<p>The observed performance ceiling in Stage 3, where all nine baseline architectures achieved ROC-AUC &gt;0.977 despite spanning 1-3 layers and 16-64 units, indicates that the strong predictive signal from academic performance features enables robust prediction regardless of model complexity. The narrow variance across architectures (span of only 0.007 in ROC-AUC) and the failure of regularization to improve upon baseline performance suggest that practitioners can deploy simpler, computationally efficient configurations without sacrificing predictive accuracy. For resource-constrained institutions, this finding reduces technical barriers to adoption: effective early warning systems can be deployed using conservatively tuned or even default neural network configurations, avoiding extensive computational search.</p>
</section>
<section id="class-imbalance-and-evaluation-considerations" class="level3">
<h3 class="anchored" data-anchor-id="class-imbalance-and-evaluation-considerations">Class Imbalance and Evaluation Considerations</h3>
<p>The training approach using natural class distributions (~85% completion, ~15% dropout) without synthetic oversampling techniques represents both methodological strength and practical limitation. Training on natural distributions ensures model predictions reflect real-world base rates, avoiding potential artifacts from synthetically generated examples that could distort decision boundaries. However, standard loss functions (sparse categorical cross-entropy) optimize overall accuracy, which may not align with institutional priorities placing higher value on recall (identifying at-risk students) even at cost of reduced precision (more false alarms).</p>
<p>The achieved performance metrics demonstrate that Stage 3 models maintain strong minority class identification despite class imbalance. The best baseline model (Model_5_2L_32U) correctly identified 519 of 586 dropout cases on the test set (recall=0.965) while maintaining high precision (0.980), indicating effective decision boundary learning without explicit class balancing. However, institutions with different cost structures, where missing a true dropout carries substantially higher operational cost than providing unnecessary intervention, may benefit from cost-sensitive loss functions that explicitly penalize false negatives more heavily than false positives. This modification would shift the model’s operating point along the ROC curve toward higher recall at acceptable precision trade-offs.</p>
</section>
<section id="practical-deployment-framework" class="level3">
<h3 class="anchored" data-anchor-id="practical-deployment-framework">Practical Deployment Framework</h3>
<p>The progressive data enrichment analysis provides actionable guidance for multi-stage early warning system deployment. Institutions can implement temporal risk assessment updates that balance early intervention imperatives against prediction accuracy: deploy Stage 1 models (ROC-AUC ~0.85) for initial enrollment screening to identify high-risk cohorts, refine predictions with Stage 2 mid-semester updates (ROC-AUC ~0.887) incorporating engagement metrics, and leverage Stage 3 models (ROC-AUC &gt;0.98) for end-of-term comprehensive assessment enabling targeted retention interventions for the subsequent term.</p>
<p>This staged approach enables institutions to optimize intervention timing based on available resources and risk tolerance. Stage 1’s moderate discrimination (ROC-AUC ~0.85) may suffice for broad preventive programs targeting larger at-risk populations with lower-intensity interventions, while Stage 3’s exceptional discrimination (ROC-AUC &gt;0.98) enables precise targeting of intensive support services toward students with highest dropout probability. Within each stage, threshold adjustment provides additional flexibility for balancing precision and recall: conservative thresholds minimize false positives for resource-constrained programs, while aggressive thresholds maximize coverage for comprehensive support initiatives.</p>
</section>
</section>
<section id="conclusion" class="level2">
<h2 class="anchored" data-anchor-id="conclusion">Conclusion</h2>
<p>This analysis demonstrates that neural networks achieve exceptional dropout prediction performance (ROC-AUC &gt;0.98, F1 &gt;0.97) when trained on comprehensive end-of-semester academic data, substantially outperforming predictions based on demographic and early engagement features alone. The systematic comparison across three progressive data stages quantifies a clear performance hierarchy: enrollment features (ROC-AUC ~0.85) &lt; mid-semester engagement (ROC-AUC ~0.887) &lt; end-of-semester academics (ROC-AUC &gt;0.98), establishing empirical benchmarks for institutional expectations at each temporal decision point.</p>
<p>The key methodological finding that data enrichment overwhelms architectural optimization in importance provides actionable guidance for practitioners: prioritize data collection, feature engineering (particularly academic performance metrics like RateModuleSuccess), and timely data availability over extensive hyperparameter tuning or complex architectures. Simpler baseline configurations (2 layers, 32-64 units, dropout=0.2, learning rate=0.001) achieve near-ceiling performance when trained on high-quality features, reducing implementation complexity and computational requirements for resource-constrained institutions.</p>
</section>
<section id="references" class="level2">
<h2 class="anchored" data-anchor-id="references">References</h2>
<div id="refs" class="references csl-bib-body hanging-indent" data-entry-spacing="0" role="list">
<div id="ref-abadi2016tensorflow" class="csl-entry" role="listitem">
Abadi, Martín, Paul Barham, Jianmin Chen, Zhifeng Chen, Andy Davis, Jeffrey Dean, Matthieu Devin, et al. 2016. <span>“TensorFlow: A System for Large-Scale Machine Learning.”</span> <em>Proceedings of the 12th USENIX Symposium on Operating Systems Design and Implementation</em>, 265–83.
</div>
<div id="ref-goren2024early" class="csl-entry" role="listitem">
Goren, Or, Liron Cohen, and Amir Rubinstein. 2024. <span>“Early Prediction of Student Dropout in Higher Education Using Machine Learning Models.”</span> <em>Educational Data Mining</em>. <a href="https://doi.org/10.5281/zenodo.12729834">https://doi.org/10.5281/zenodo.12729834</a>.
</div>
<div id="ref-pedregosa2011scikitlearn" class="csl-entry" role="listitem">
Pedregosa, Fabian, Gaël Varoquaux, Alexandre Gramfort, Vincent Michel, Bertrand Thirion, Olivier Grisel, Mathieu Blondel, et al. 2011. <span>“Scikit-Learn: Machine Learning in Python.”</span> <em>Journal of Machine Learning Research</em> 12: 2825–30.
</div>
</div>


</section>

</main> <!-- /main -->
<script id="quarto-html-after-body" type="application/javascript">
window.document.addEventListener("DOMContentLoaded", function (event) {
  const toggleBodyColorMode = (bsSheetEl) => {
    const mode = bsSheetEl.getAttribute("data-mode");
    const bodyEl = window.document.querySelector("body");
    if (mode === "dark") {
      bodyEl.classList.add("quarto-dark");
      bodyEl.classList.remove("quarto-light");
    } else {
      bodyEl.classList.add("quarto-light");
      bodyEl.classList.remove("quarto-dark");
    }
  }
  const toggleBodyColorPrimary = () => {
    const bsSheetEl = window.document.querySelector("link#quarto-bootstrap");
    if (bsSheetEl) {
      toggleBodyColorMode(bsSheetEl);
    }
  }
  toggleBodyColorPrimary();  
  const icon = "";
  const anchorJS = new window.AnchorJS();
  anchorJS.options = {
    placement: 'right',
    icon: icon
  };
  anchorJS.add('.anchored');
  const isCodeAnnotation = (el) => {
    for (const clz of el.classList) {
      if (clz.startsWith('code-annotation-')) {                     
        return true;
      }
    }
    return false;
  }
  const onCopySuccess = function(e) {
    // button target
    const button = e.trigger;
    // don't keep focus
    button.blur();
    // flash "checked"
    button.classList.add('code-copy-button-checked');
    var currentTitle = button.getAttribute("title");
    button.setAttribute("title", "Copied!");
    let tooltip;
    if (window.bootstrap) {
      button.setAttribute("data-bs-toggle", "tooltip");
      button.setAttribute("data-bs-placement", "left");
      button.setAttribute("data-bs-title", "Copied!");
      tooltip = new bootstrap.Tooltip(button, 
        { trigger: "manual", 
          customClass: "code-copy-button-tooltip",
          offset: [0, -8]});
      tooltip.show();    
    }
    setTimeout(function() {
      if (tooltip) {
        tooltip.hide();
        button.removeAttribute("data-bs-title");
        button.removeAttribute("data-bs-toggle");
        button.removeAttribute("data-bs-placement");
      }
      button.setAttribute("title", currentTitle);
      button.classList.remove('code-copy-button-checked');
    }, 1000);
    // clear code selection
    e.clearSelection();
  }
  const getTextToCopy = function(trigger) {
      const codeEl = trigger.previousElementSibling.cloneNode(true);
      for (const childEl of codeEl.children) {
        if (isCodeAnnotation(childEl)) {
          childEl.remove();
        }
      }
      return codeEl.innerText;
  }
  const clipboard = new window.ClipboardJS('.code-copy-button:not([data-in-quarto-modal])', {
    text: getTextToCopy
  });
  clipboard.on('success', onCopySuccess);
  if (window.document.getElementById('quarto-embedded-source-code-modal')) {
    const clipboardModal = new window.ClipboardJS('.code-copy-button[data-in-quarto-modal]', {
      text: getTextToCopy,
      container: window.document.getElementById('quarto-embedded-source-code-modal')
    });
    clipboardModal.on('success', onCopySuccess);
  }
    var localhostRegex = new RegExp(/^(?:http|https):\/\/localhost\:?[0-9]*\//);
    var mailtoRegex = new RegExp(/^mailto:/);
      var filterRegex = new RegExp("https:\/\/rodrigograndy\.github\.io");
    var isInternal = (href) => {
        return filterRegex.test(href) || localhostRegex.test(href) || mailtoRegex.test(href);
    }
    // Inspect non-navigation links and adorn them if external
 	var links = window.document.querySelectorAll('a[href]:not(.nav-link):not(.navbar-brand):not(.toc-action):not(.sidebar-link):not(.sidebar-item-toggle):not(.pagination-link):not(.no-external):not([aria-hidden]):not(.dropdown-item):not(.quarto-navigation-tool):not(.about-link)');
    for (var i=0; i<links.length; i++) {
      const link = links[i];
      if (!isInternal(link.href)) {
        // undo the damage that might have been done by quarto-nav.js in the case of
        // links that we want to consider external
        if (link.dataset.originalHref !== undefined) {
          link.href = link.dataset.originalHref;
        }
          // target, if specified
          link.setAttribute("target", "_blank");
          if (link.getAttribute("rel") === null) {
            link.setAttribute("rel", "noopener");
          }
      }
    }
  function tippyHover(el, contentFn, onTriggerFn, onUntriggerFn) {
    const config = {
      allowHTML: true,
      maxWidth: 500,
      delay: 100,
      arrow: false,
      appendTo: function(el) {
          return el.parentElement;
      },
      interactive: true,
      interactiveBorder: 10,
      theme: 'quarto',
      placement: 'bottom-start',
    };
    if (contentFn) {
      config.content = contentFn;
    }
    if (onTriggerFn) {
      config.onTrigger = onTriggerFn;
    }
    if (onUntriggerFn) {
      config.onUntrigger = onUntriggerFn;
    }
    window.tippy(el, config); 
  }
  const noterefs = window.document.querySelectorAll('a[role="doc-noteref"]');
  for (var i=0; i<noterefs.length; i++) {
    const ref = noterefs[i];
    tippyHover(ref, function() {
      // use id or data attribute instead here
      let href = ref.getAttribute('data-footnote-href') || ref.getAttribute('href');
      try { href = new URL(href).hash; } catch {}
      const id = href.replace(/^#\/?/, "");
      const note = window.document.getElementById(id);
      if (note) {
        return note.innerHTML;
      } else {
        return "";
      }
    });
  }
  const xrefs = window.document.querySelectorAll('a.quarto-xref');
  const processXRef = (id, note) => {
    // Strip column container classes
    const stripColumnClz = (el) => {
      el.classList.remove("page-full", "page-columns");
      if (el.children) {
        for (const child of el.children) {
          stripColumnClz(child);
        }
      }
    }
    stripColumnClz(note)
    if (id === null || id.startsWith('sec-')) {
      // Special case sections, only their first couple elements
      const container = document.createElement("div");
      if (note.children && note.children.length > 2) {
        container.appendChild(note.children[0].cloneNode(true));
        for (let i = 1; i < note.children.length; i++) {
          const child = note.children[i];
          if (child.tagName === "P" && child.innerText === "") {
            continue;
          } else {
            container.appendChild(child.cloneNode(true));
            break;
          }
        }
        if (window.Quarto?.typesetMath) {
          window.Quarto.typesetMath(container);
        }
        return container.innerHTML
      } else {
        if (window.Quarto?.typesetMath) {
          window.Quarto.typesetMath(note);
        }
        return note.innerHTML;
      }
    } else {
      // Remove any anchor links if they are present
      const anchorLink = note.querySelector('a.anchorjs-link');
      if (anchorLink) {
        anchorLink.remove();
      }
      if (window.Quarto?.typesetMath) {
        window.Quarto.typesetMath(note);
      }
      if (note.classList.contains("callout")) {
        return note.outerHTML;
      } else {
        return note.innerHTML;
      }
    }
  }
  for (var i=0; i<xrefs.length; i++) {
    const xref = xrefs[i];
    tippyHover(xref, undefined, function(instance) {
      instance.disable();
      let url = xref.getAttribute('href');
      let hash = undefined; 
      if (url.startsWith('#')) {
        hash = url;
      } else {
        try { hash = new URL(url).hash; } catch {}
      }
      if (hash) {
        const id = hash.replace(/^#\/?/, "");
        const note = window.document.getElementById(id);
        if (note !== null) {
          try {
            const html = processXRef(id, note.cloneNode(true));
            instance.setContent(html);
          } finally {
            instance.enable();
            instance.show();
          }
        } else {
          // See if we can fetch this
          fetch(url.split('#')[0])
          .then(res => res.text())
          .then(html => {
            const parser = new DOMParser();
            const htmlDoc = parser.parseFromString(html, "text/html");
            const note = htmlDoc.getElementById(id);
            if (note !== null) {
              const html = processXRef(id, note);
              instance.setContent(html);
            } 
          }).finally(() => {
            instance.enable();
            instance.show();
          });
        }
      } else {
        // See if we can fetch a full url (with no hash to target)
        // This is a special case and we should probably do some content thinning / targeting
        fetch(url)
        .then(res => res.text())
        .then(html => {
          const parser = new DOMParser();
          const htmlDoc = parser.parseFromString(html, "text/html");
          const note = htmlDoc.querySelector('main.content');
          if (note !== null) {
            // This should only happen for chapter cross references
            // (since there is no id in the URL)
            // remove the first header
            if (note.children.length > 0 && note.children[0].tagName === "HEADER") {
              note.children[0].remove();
            }
            const html = processXRef(null, note);
            instance.setContent(html);
          } 
        }).finally(() => {
          instance.enable();
          instance.show();
        });
      }
    }, function(instance) {
    });
  }
      let selectedAnnoteEl;
      const selectorForAnnotation = ( cell, annotation) => {
        let cellAttr = 'data-code-cell="' + cell + '"';
        let lineAttr = 'data-code-annotation="' +  annotation + '"';
        const selector = 'span[' + cellAttr + '][' + lineAttr + ']';
        return selector;
      }
      const selectCodeLines = (annoteEl) => {
        const doc = window.document;
        const targetCell = annoteEl.getAttribute("data-target-cell");
        const targetAnnotation = annoteEl.getAttribute("data-target-annotation");
        const annoteSpan = window.document.querySelector(selectorForAnnotation(targetCell, targetAnnotation));
        const lines = annoteSpan.getAttribute("data-code-lines").split(",");
        const lineIds = lines.map((line) => {
          return targetCell + "-" + line;
        })
        let top = null;
        let height = null;
        let parent = null;
        if (lineIds.length > 0) {
            //compute the position of the single el (top and bottom and make a div)
            const el = window.document.getElementById(lineIds[0]);
            top = el.offsetTop;
            height = el.offsetHeight;
            parent = el.parentElement.parentElement;
          if (lineIds.length > 1) {
            const lastEl = window.document.getElementById(lineIds[lineIds.length - 1]);
            const bottom = lastEl.offsetTop + lastEl.offsetHeight;
            height = bottom - top;
          }
          if (top !== null && height !== null && parent !== null) {
            // cook up a div (if necessary) and position it 
            let div = window.document.getElementById("code-annotation-line-highlight");
            if (div === null) {
              div = window.document.createElement("div");
              div.setAttribute("id", "code-annotation-line-highlight");
              div.style.position = 'absolute';
              parent.appendChild(div);
            }
            div.style.top = top - 2 + "px";
            div.style.height = height + 4 + "px";
            div.style.left = 0;
            let gutterDiv = window.document.getElementById("code-annotation-line-highlight-gutter");
            if (gutterDiv === null) {
              gutterDiv = window.document.createElement("div");
              gutterDiv.setAttribute("id", "code-annotation-line-highlight-gutter");
              gutterDiv.style.position = 'absolute';
              const codeCell = window.document.getElementById(targetCell);
              const gutter = codeCell.querySelector('.code-annotation-gutter');
              gutter.appendChild(gutterDiv);
            }
            gutterDiv.style.top = top - 2 + "px";
            gutterDiv.style.height = height + 4 + "px";
          }
          selectedAnnoteEl = annoteEl;
        }
      };
      const unselectCodeLines = () => {
        const elementsIds = ["code-annotation-line-highlight", "code-annotation-line-highlight-gutter"];
        elementsIds.forEach((elId) => {
          const div = window.document.getElementById(elId);
          if (div) {
            div.remove();
          }
        });
        selectedAnnoteEl = undefined;
      };
        // Handle positioning of the toggle
    window.addEventListener(
      "resize",
      throttle(() => {
        elRect = undefined;
        if (selectedAnnoteEl) {
          selectCodeLines(selectedAnnoteEl);
        }
      }, 10)
    );
    function throttle(fn, ms) {
    let throttle = false;
    let timer;
      return (...args) => {
        if(!throttle) { // first call gets through
            fn.apply(this, args);
            throttle = true;
        } else { // all the others get throttled
            if(timer) clearTimeout(timer); // cancel #2
            timer = setTimeout(() => {
              fn.apply(this, args);
              timer = throttle = false;
            }, ms);
        }
      };
    }
      // Attach click handler to the DT
      const annoteDls = window.document.querySelectorAll('dt[data-target-cell]');
      for (const annoteDlNode of annoteDls) {
        annoteDlNode.addEventListener('click', (event) => {
          const clickedEl = event.target;
          if (clickedEl !== selectedAnnoteEl) {
            unselectCodeLines();
            const activeEl = window.document.querySelector('dt[data-target-cell].code-annotation-active');
            if (activeEl) {
              activeEl.classList.remove('code-annotation-active');
            }
            selectCodeLines(clickedEl);
            clickedEl.classList.add('code-annotation-active');
          } else {
            // Unselect the line
            unselectCodeLines();
            clickedEl.classList.remove('code-annotation-active');
          }
        });
      }
  const findCites = (el) => {
    const parentEl = el.parentElement;
    if (parentEl) {
      const cites = parentEl.dataset.cites;
      if (cites) {
        return {
          el,
          cites: cites.split(' ')
        };
      } else {
        return findCites(el.parentElement)
      }
    } else {
      return undefined;
    }
  };
  var bibliorefs = window.document.querySelectorAll('a[role="doc-biblioref"]');
  for (var i=0; i<bibliorefs.length; i++) {
    const ref = bibliorefs[i];
    const citeInfo = findCites(ref);
    if (citeInfo) {
      tippyHover(citeInfo.el, function() {
        var popup = window.document.createElement('div');
        citeInfo.cites.forEach(function(cite) {
          var citeDiv = window.document.createElement('div');
          citeDiv.classList.add('hanging-indent');
          citeDiv.classList.add('csl-entry');
          var biblioDiv = window.document.getElementById('ref-' + cite);
          if (biblioDiv) {
            citeDiv.innerHTML = biblioDiv.innerHTML;
          }
          popup.appendChild(citeDiv);
        });
        return popup.innerHTML;
      });
    }
  }
});
</script>
</div> <!-- /content -->
<footer class="footer">
  <div class="nav-footer">
    <div class="nav-footer-left">
      &nbsp;
    </div>   
    <div class="nav-footer-center">
<p>© 2025 Rodrigo Grandy</p>
</div>
    <div class="nav-footer-right">
      &nbsp;
    </div>
  </div>
</footer>




</body></html>