project:
  type: website
  
website:
  site-url: https://rgrandym.github.io
  description: "Data Science Blog and Portfolio of Rodrigo Grandy"
  navbar:
    background: "#00003E"
    left:
      - href: index.qmd
        text: Home
      - href: projects.qmd
        text: Projects
      - href: cv.qmd
        text: CV
    footer:
      copyright: "© 2023 Rodrigo Grandy"

format:
  html:
    page-layout: full
    css: styles/styles.css
    include-in-header:
      text: |
        <style>
          :root {
            --content-width: 1400px;
            --side-padding: 5vw;      /* Responsive side padding */
          }
        </style>
